/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tikhub.client.api;

import io.tikhub.client.ApiException;
import org.openapitools.client.model.HttpValidationError;
import org.openapitools.client.model.ResponseModel;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DouyinXingtuApiApi
 */
public class DouyinXingtuApiApiTest {

    private final DouyinXingtuApiApi api = new DouyinXingtuApiApi();

    /**
     * 获取kol热词分析内容V1/Get Author Content Hot Comment Keywords V1
     *
     * # [中文] ### 用途: - 获取kol热词分析内容V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol热词分析内容  # [English] ### Purpose: - Get Author Content Hot Comment Keywords V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - Author Content Hot Comment Keywords  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorContentHotCommentKeywordsV1ApiV1DouyinXingtuAuthorContentHotCommentKeywordsV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.authorContentHotCommentKeywordsV1ApiV1DouyinXingtuAuthorContentHotCommentKeywordsV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol热词分析内容V1/Get Author Content Hot Comment Keywords V1
     *
     * # [中文] ### 用途: - 获取kol热词分析内容V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol热词分析内容  # [English] ### Purpose: - Get Author Content Hot Comment Keywords V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - Author Content Hot Comment Keywords  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorContentHotCommentKeywordsV1ApiV1DouyinXingtuAuthorContentHotCommentKeywordsV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.authorContentHotCommentKeywordsV1ApiV1DouyinXingtuAuthorContentHotCommentKeywordsV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol热词分析评论V1/Get Author Hot Comment Tokens V1
     *
     * # [中文] ### 用途: - 获取kol热词分析评论V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol热词分析评论  # [English] ### Purpose: - Get Author Hot Comment Tokens V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - Author Hot Comment Tokens  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorHotCommentTokensV1ApiV1DouyinXingtuAuthorHotCommentTokensV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.authorHotCommentTokensV1ApiV1DouyinXingtuAuthorHotCommentTokensV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol热词分析评论V1/Get Author Hot Comment Tokens V1
     *
     * # [中文] ### 用途: - 获取kol热词分析评论V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol热词分析评论  # [English] ### Purpose: - Get Author Hot Comment Tokens V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - Author Hot Comment Tokens  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorHotCommentTokensV1ApiV1DouyinXingtuAuthorHotCommentTokensV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.authorHotCommentTokensV1ApiV1DouyinXingtuAuthorHotCommentTokensV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 根据抖音sec_user_id获取游客星图kolid/Get XingTu kolid by Douyin sec_user_id
     *
     * # [中文] ### 用途: - 通过抖音sec_user_id获取游客星图kolid - 价格：0.001$ / 次 ### 参数: - sec_user_id: sec_user_id, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### 返回: - 游客星图kolid  # [English] ### Purpose: - Get XingTu kolid by Douyin sec_user_id - Price: 0.001$ / time ### Parameters: - sec_user_id: sec_user_id, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### Return: - XingTu kolid  # [示例/Example] sec_user_id &#x3D; \&quot;MS4wLjABAAAAoxwUZouIdKL6sZ8EB96KDjkrhfBMS1KbCgsMJR1kIUs\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getXingtuKolidBySecUserIdApiV1DouyinXingtuGetXingtuKolidBySecUserIdGetTest() throws ApiException {
        //
        //String secUserId = null;
        //
        //ResponseModel response = api.getXingtuKolidBySecUserIdApiV1DouyinXingtuGetXingtuKolidBySecUserIdGet(secUserId);

        // TODO: test validations
    }
    /**
     * 根据抖音sec_user_id获取游客星图kolid/Get XingTu kolid by Douyin sec_user_id
     *
     * # [中文] ### 用途: - 通过抖音sec_user_id获取游客星图kolid - 价格：0.001$ / 次 ### 参数: - sec_user_id: sec_user_id, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### 返回: - 游客星图kolid  # [English] ### Purpose: - Get XingTu kolid by Douyin sec_user_id - Price: 0.001$ / time ### Parameters: - sec_user_id: sec_user_id, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### Return: - XingTu kolid  # [示例/Example] sec_user_id &#x3D; \&quot;MS4wLjABAAAAoxwUZouIdKL6sZ8EB96KDjkrhfBMS1KbCgsMJR1kIUs\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getXingtuKolidBySecUserIdApiV1DouyinXingtuGetXingtuKolidBySecUserIdGet_0Test() throws ApiException {
        //
        //String secUserId = null;
        //
        //ResponseModel response = api.getXingtuKolidBySecUserIdApiV1DouyinXingtuGetXingtuKolidBySecUserIdGet_0(secUserId);

        // TODO: test validations
    }
    /**
     * 根据抖音用户ID获取游客星图kolid/Get XingTu kolid by Douyin User ID
     *
     * # [中文] ### 用途: - 通过抖音用户ID获取游客星图kolid - 价格：0.001$ / 次 ### 参数: - uid: 用户ID, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/web/fetch_user_profile_by_uid&#x60;     - &#x60;/api/v1/douyin/web/fetch_user_profile_by_short_id&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### 返回: - 游客星图kolid  # [English] ### Purpose: - Get XingTu kolid by Douyin User ID - Price: 0.001$ / time ### Parameters: - uid: User ID, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/web/fetch_user_profile_by_uid&#x60;     - &#x60;/api/v1/douyin/web/fetch_user_profile_by_short_id&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### Return: - XingTu kolid  # [示例/Example] uid &#x3D; \&quot;70452002324\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getXingtuKolidByUidApiV1DouyinXingtuGetXingtuKolidByUidGetTest() throws ApiException {
        //
        //String uid = null;
        //
        //ResponseModel response = api.getXingtuKolidByUidApiV1DouyinXingtuGetXingtuKolidByUidGet(uid);

        // TODO: test validations
    }
    /**
     * 根据抖音用户ID获取游客星图kolid/Get XingTu kolid by Douyin User ID
     *
     * # [中文] ### 用途: - 通过抖音用户ID获取游客星图kolid - 价格：0.001$ / 次 ### 参数: - uid: 用户ID, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/web/fetch_user_profile_by_uid&#x60;     - &#x60;/api/v1/douyin/web/fetch_user_profile_by_short_id&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### 返回: - 游客星图kolid  # [English] ### Purpose: - Get XingTu kolid by Douyin User ID - Price: 0.001$ / time ### Parameters: - uid: User ID, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/web/fetch_user_profile_by_uid&#x60;     - &#x60;/api/v1/douyin/web/fetch_user_profile_by_short_id&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### Return: - XingTu kolid  # [示例/Example] uid &#x3D; \&quot;70452002324\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getXingtuKolidByUidApiV1DouyinXingtuGetXingtuKolidByUidGet_0Test() throws ApiException {
        //
        //String uid = null;
        //
        //ResponseModel response = api.getXingtuKolidByUidApiV1DouyinXingtuGetXingtuKolidByUidGet_0(uid);

        // TODO: test validations
    }
    /**
     * 根据抖音号获取游客星图kolid/Get XingTu kolid by Douyin unique_id
     *
     * # [中文] ### 用途: - 通过抖音号获取游客星图kolid - 价格：0.001$ / 次 ### 参数: - unique_id: 抖音号, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### 返回: - 游客星图kolid  # [English] ### Purpose: - Get XingTu kolid by Douyin unique_id - Price: 0.001$ / time ### Parameters: - unique_id: unique_id, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### Return: - XingTu kolid  # [示例/Example] unique_id &#x3D; \&quot;m6640150\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getXingtuKolidByUniqueIdApiV1DouyinXingtuGetXingtuKolidByUniqueIdGetTest() throws ApiException {
        //
        //String uniqueId = null;
        //
        //ResponseModel response = api.getXingtuKolidByUniqueIdApiV1DouyinXingtuGetXingtuKolidByUniqueIdGet(uniqueId);

        // TODO: test validations
    }
    /**
     * 根据抖音号获取游客星图kolid/Get XingTu kolid by Douyin unique_id
     *
     * # [中文] ### 用途: - 通过抖音号获取游客星图kolid - 价格：0.001$ / 次 ### 参数: - unique_id: 抖音号, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### 返回: - 游客星图kolid  # [English] ### Purpose: - Get XingTu kolid by Douyin unique_id - Price: 0.001$ / time ### Parameters: - unique_id: unique_id, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/web/handler_user_profile&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v2&#x60;     - &#x60;/api/v1/douyin/web/handler_user_profile_v3&#x60;     - &#x60;/api/v1/douyin/app/v3/handler_user_profile&#x60; ### Return: - XingTu kolid  # [示例/Example] unique_id &#x3D; \&quot;m6640150\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getXingtuKolidByUniqueIdApiV1DouyinXingtuGetXingtuKolidByUniqueIdGet_0Test() throws ApiException {
        //
        //String uniqueId = null;
        //
        //ResponseModel response = api.getXingtuKolidByUniqueIdApiV1DouyinXingtuGetXingtuKolidByUniqueIdGet_0(uniqueId);

        // TODO: test validations
    }
    /**
     * 获取kol观众画像V1/Get kol Audience Portrait V1
     *
     * # [中文] ### 用途: - 获取kol观众画像V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol观众画像  # [English] ### Purpose: - Get kol Audience Portrait V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Audience Portrait  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolAudiencePortraitV1ApiV1DouyinXingtuKolAudiencePortraitV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolAudiencePortraitV1ApiV1DouyinXingtuKolAudiencePortraitV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol观众画像V1/Get kol Audience Portrait V1
     *
     * # [中文] ### 用途: - 获取kol观众画像V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol观众画像  # [English] ### Purpose: - Get kol Audience Portrait V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Audience Portrait  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolAudiencePortraitV1ApiV1DouyinXingtuKolAudiencePortraitV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolAudiencePortraitV1ApiV1DouyinXingtuKolAudiencePortraitV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol基本信息V1/Get kol Base Info V1
     *
     * # [中文] ### 用途: - 获取kol基本信息V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - platformChannel:     - 平台渠道，支持以下参数:     - _1 :抖音短视频(Video)     - _10 :抖音直播(Live) ### 返回: - kol基本信息  # [English] ### Purpose: - Get kol Base Info V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - platformChannel:     - Platform channel, supports the following parameters:     - _1 :Douyin Video     - _10 :Douyin Live ### Return: - kol Base Info  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; platformChannel &#x3D; \&quot;_1\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolBaseInfoV1ApiV1DouyinXingtuKolBaseInfoV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //String platformChannel = null;
        //
        //ResponseModel response = api.kolBaseInfoV1ApiV1DouyinXingtuKolBaseInfoV1Get(kolId, platformChannel);

        // TODO: test validations
    }
    /**
     * 获取kol基本信息V1/Get kol Base Info V1
     *
     * # [中文] ### 用途: - 获取kol基本信息V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - platformChannel:     - 平台渠道，支持以下参数:     - _1 :抖音短视频(Video)     - _10 :抖音直播(Live) ### 返回: - kol基本信息  # [English] ### Purpose: - Get kol Base Info V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - platformChannel:     - Platform channel, supports the following parameters:     - _1 :Douyin Video     - _10 :Douyin Live ### Return: - kol Base Info  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; platformChannel &#x3D; \&quot;_1\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolBaseInfoV1ApiV1DouyinXingtuKolBaseInfoV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //String platformChannel = null;
        //
        //ResponseModel response = api.kolBaseInfoV1ApiV1DouyinXingtuKolBaseInfoV1Get_0(kolId, platformChannel);

        // TODO: test validations
    }
    /**
     * 获取kol转化能力分析V1/Get kol Conversion Ability Analysis V1
     *
     * # [中文] ### 用途: - 获取kol转化能力分析V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - _range: 时间范围, 支持以下参数:     - _1 :近7天(last 7 days)     - _2 :30天(last 30 days)     - _3 :90天(last 90 days) ### 返回: - kol转化能力分析  # [English] ### Purpose: - Get kol Conversion Ability Analysis V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - _range: Time range, supports the following parameters:     - _1 :Last 7 days     - _2 :Last 30 days     - _3 :Last 90 days ### Return: - kol Conversion Ability Analysis  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; _range &#x3D; \&quot;_1\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolConversionAbilityAnalysisV1ApiV1DouyinXingtuKolConversionAbilityAnalysisV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //String range = null;
        //
        //ResponseModel response = api.kolConversionAbilityAnalysisV1ApiV1DouyinXingtuKolConversionAbilityAnalysisV1Get(kolId, range);

        // TODO: test validations
    }
    /**
     * 获取kol转化能力分析V1/Get kol Conversion Ability Analysis V1
     *
     * # [中文] ### 用途: - 获取kol转化能力分析V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - _range: 时间范围, 支持以下参数:     - _1 :近7天(last 7 days)     - _2 :30天(last 30 days)     - _3 :90天(last 90 days) ### 返回: - kol转化能力分析  # [English] ### Purpose: - Get kol Conversion Ability Analysis V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - _range: Time range, supports the following parameters:     - _1 :Last 7 days     - _2 :Last 30 days     - _3 :Last 90 days ### Return: - kol Conversion Ability Analysis  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; _range &#x3D; \&quot;_1\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolConversionAbilityAnalysisV1ApiV1DouyinXingtuKolConversionAbilityAnalysisV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //String range = null;
        //
        //ResponseModel response = api.kolConversionAbilityAnalysisV1ApiV1DouyinXingtuKolConversionAbilityAnalysisV1Get_0(kolId, range);

        // TODO: test validations
    }
    /**
     * 获取kol转化视频展示V1/Get kol Convert Video Display V1
     *
     * # [中文] ### 用途: - 获取kol转化视频展示V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - detailType: 详情类型, 支持以下参数:     - _1 :相关视频数据(Video Data)     - _2 :相关商品数据(Product Data) ### 返回: - kol转化视频展示  # [English] ### Purpose: - Get kol Convert Video Display V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - detailType: Detail type, supports the following parameters:     - _1 :Video Data     - _2 :Product Data - page: Page number, starting from 1 ### Return: - kol Convert Video Display  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; detailType &#x3D; \&quot;_1\&quot; page &#x3D; 1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolConvertVideoDisplayV1ApiV1DouyinXingtuKolConvertVideoDisplayV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //String detailType = null;
        //
        //Integer page = null;
        //
        //ResponseModel response = api.kolConvertVideoDisplayV1ApiV1DouyinXingtuKolConvertVideoDisplayV1Get(kolId, detailType, page);

        // TODO: test validations
    }
    /**
     * 获取kol转化视频展示V1/Get kol Convert Video Display V1
     *
     * # [中文] ### 用途: - 获取kol转化视频展示V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - detailType: 详情类型, 支持以下参数:     - _1 :相关视频数据(Video Data)     - _2 :相关商品数据(Product Data) ### 返回: - kol转化视频展示  # [English] ### Purpose: - Get kol Convert Video Display V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - detailType: Detail type, supports the following parameters:     - _1 :Video Data     - _2 :Product Data - page: Page number, starting from 1 ### Return: - kol Convert Video Display  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; detailType &#x3D; \&quot;_1\&quot; page &#x3D; 1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolConvertVideoDisplayV1ApiV1DouyinXingtuKolConvertVideoDisplayV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //String detailType = null;
        //
        //Integer page = null;
        //
        //ResponseModel response = api.kolConvertVideoDisplayV1ApiV1DouyinXingtuKolConvertVideoDisplayV1Get_0(kolId, detailType, page);

        // TODO: test validations
    }
    /**
     * 获取kol性价比能力分析V1/Get kol Cp Info V1
     *
     * # [中文] ### 用途: - 获取kol性价比能力分析V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol性价比能力分析  # [English] ### Purpose: - Get kol Cp Info V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Cp Info  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolCpInfoV1ApiV1DouyinXingtuKolCpInfoV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolCpInfoV1ApiV1DouyinXingtuKolCpInfoV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol性价比能力分析V1/Get kol Cp Info V1
     *
     * # [中文] ### 用途: - 获取kol性价比能力分析V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol性价比能力分析  # [English] ### Purpose: - Get kol Cp Info V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Cp Info  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolCpInfoV1ApiV1DouyinXingtuKolCpInfoV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolCpInfoV1ApiV1DouyinXingtuKolCpInfoV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol粉丝趋势V1/Get kol Daily Fnas V1
     *
     * # [中文] ### 用途: - 获取kol粉丝趋势V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - startDate: 开始日期，格式为：yyyy-MM-dd - endDate: 结束日期，格式为：yyyy-MM-dd ### 返回: - kol粉丝趋势  # [English] ### Purpose: - Get kol Daily Fans V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - startDate: Start date, format: yyyy-MM-dd - endDate: End date, format: yyyy-MM-dd ### Return: - kol Daily Fans  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; startDate &#x3D; \&quot;2024-12-01\&quot; endDate &#x3D; \&quot;2025-01-01\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolDailyFansV1ApiV1DouyinXingtuKolDailyFansV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //String startDate = null;
        //
        //String endDate = null;
        //
        //ResponseModel response = api.kolDailyFansV1ApiV1DouyinXingtuKolDailyFansV1Get(kolId, startDate, endDate);

        // TODO: test validations
    }
    /**
     * 获取kol粉丝趋势V1/Get kol Daily Fnas V1
     *
     * # [中文] ### 用途: - 获取kol粉丝趋势V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - startDate: 开始日期，格式为：yyyy-MM-dd - endDate: 结束日期，格式为：yyyy-MM-dd ### 返回: - kol粉丝趋势  # [English] ### Purpose: - Get kol Daily Fans V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - startDate: Start date, format: yyyy-MM-dd - endDate: End date, format: yyyy-MM-dd ### Return: - kol Daily Fans  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; startDate &#x3D; \&quot;2024-12-01\&quot; endDate &#x3D; \&quot;2025-01-01\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolDailyFansV1ApiV1DouyinXingtuKolDailyFansV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //String startDate = null;
        //
        //String endDate = null;
        //
        //ResponseModel response = api.kolDailyFansV1ApiV1DouyinXingtuKolDailyFansV1Get_0(kolId, startDate, endDate);

        // TODO: test validations
    }
    /**
     * 获取kol数据概览V1/Get kol Data Overview V1
     *
     * # [中文] ### 用途: - 获取kol数据概览V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - _type: 类型, 支持以下参数:     - _1 :个人视频(personal video)     - _2 :星图视频(xingtu video) - _range: 范围, 支持以下参数:     - _2 :近30天(last 30 days)     - _3 :近90天(last 90 days) - flowType: 流量类型, 支持以下参数:     - 1 : 默认(default) ### 返回: - kol数据概览  # [English] ### Purpose: - Get kol Data Overview V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - _type: Type, supports the following parameters:     - _1 :Personal Video     - _2 :Xingtu Video - _range: Range, supports the following parameters:     - _2 :Last 30 days     - _3 :Last 90 days - flowType: Flow Type, supports the following parameters:     - 1 : Default ### Return: - kol Data Overview  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; _type &#x3D; \&quot;_1\&quot; _range &#x3D; \&quot;_2\&quot; flowType &#x3D; 1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolDataOverviewV1ApiV1DouyinXingtuKolDataOverviewV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //String type = null;
        //
        //String range = null;
        //
        //Integer flowType = null;
        //
        //ResponseModel response = api.kolDataOverviewV1ApiV1DouyinXingtuKolDataOverviewV1Get(kolId, type, range, flowType);

        // TODO: test validations
    }
    /**
     * 获取kol数据概览V1/Get kol Data Overview V1
     *
     * # [中文] ### 用途: - 获取kol数据概览V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - _type: 类型, 支持以下参数:     - _1 :个人视频(personal video)     - _2 :星图视频(xingtu video) - _range: 范围, 支持以下参数:     - _2 :近30天(last 30 days)     - _3 :近90天(last 90 days) - flowType: 流量类型, 支持以下参数:     - 1 : 默认(default) ### 返回: - kol数据概览  # [English] ### Purpose: - Get kol Data Overview V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - _type: Type, supports the following parameters:     - _1 :Personal Video     - _2 :Xingtu Video - _range: Range, supports the following parameters:     - _2 :Last 30 days     - _3 :Last 90 days - flowType: Flow Type, supports the following parameters:     - 1 : Default ### Return: - kol Data Overview  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; _type &#x3D; \&quot;_1\&quot; _range &#x3D; \&quot;_2\&quot; flowType &#x3D; 1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolDataOverviewV1ApiV1DouyinXingtuKolDataOverviewV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //String type = null;
        //
        //String range = null;
        //
        //Integer flowType = null;
        //
        //ResponseModel response = api.kolDataOverviewV1ApiV1DouyinXingtuKolDataOverviewV1Get_0(kolId, type, range, flowType);

        // TODO: test validations
    }
    /**
     * 获取kol粉丝画像V1/Get kol Fans Portrait V1
     *
     * # [中文] ### 用途: - 获取kol粉丝画像V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol粉丝画像  # [English] ### Purpose: - Get kol Fans Portrait V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Fans Portrait  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolFansPortraitV1ApiV1DouyinXingtuKolFansPortraitV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolFansPortraitV1ApiV1DouyinXingtuKolFansPortraitV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol粉丝画像V1/Get kol Fans Portrait V1
     *
     * # [中文] ### 用途: - 获取kol粉丝画像V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol粉丝画像  # [English] ### Purpose: - Get kol Fans Portrait V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Fans Portrait  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolFansPortraitV1ApiV1DouyinXingtuKolFansPortraitV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolFansPortraitV1ApiV1DouyinXingtuKolFansPortraitV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol连接用户V1/Get kol Link Struct V1
     *
     * # [中文] ### 用途: - 获取kol连接用户V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol连接用户  # [English] ### Purpose: - Get kol Link Struct V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Link Struct  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolLinkStructV1ApiV1DouyinXingtuKolLinkStructV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolLinkStructV1ApiV1DouyinXingtuKolLinkStructV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol连接用户V1/Get kol Link Struct V1
     *
     * # [中文] ### 用途: - 获取kol连接用户V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol连接用户  # [English] ### Purpose: - Get kol Link Struct V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Link Struct  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolLinkStructV1ApiV1DouyinXingtuKolLinkStructV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolLinkStructV1ApiV1DouyinXingtuKolLinkStructV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol内容表现V1/Get kol Rec Videos V1
     *
     * # [中文] ### 用途: - 获取kol内容表现V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol内容表现  # [English] ### Purpose: - Get kol Rec Videos V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Rec Videos  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolRecVideosV1ApiV1DouyinXingtuKolRecVideosV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolRecVideosV1ApiV1DouyinXingtuKolRecVideosV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol内容表现V1/Get kol Rec Videos V1
     *
     * # [中文] ### 用途: - 获取kol内容表现V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol内容表现  # [English] ### Purpose: - Get kol Rec Videos V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Rec Videos  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolRecVideosV1ApiV1DouyinXingtuKolRecVideosV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolRecVideosV1ApiV1DouyinXingtuKolRecVideosV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol服务报价V1/Get kol Service Price V1
     *
     * # [中文] ### 用途: - 获取kol服务报价V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - platformChannel:     - 平台渠道，支持以下参数:     - _1: 抖音短视频(Video)     - _10: 抖音直播(Live) ### 返回: kol服务报价  # [English] ### Purpose: - Get kol Service Price V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - platformChannel:     - Platform channel, supports the following parameters:     - _1: Douyin Video     - _10: Douyin Live ### Return: - kol Service Price  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; platformChannel &#x3D; \&quot;_1\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolServicePriceV1ApiV1DouyinXingtuKolServicePriceV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //String platformChannel = null;
        //
        //ResponseModel response = api.kolServicePriceV1ApiV1DouyinXingtuKolServicePriceV1Get(kolId, platformChannel);

        // TODO: test validations
    }
    /**
     * 获取kol服务报价V1/Get kol Service Price V1
     *
     * # [中文] ### 用途: - 获取kol服务报价V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - platformChannel:     - 平台渠道，支持以下参数:     - _1: 抖音短视频(Video)     - _10: 抖音直播(Live) ### 返回: kol服务报价  # [English] ### Purpose: - Get kol Service Price V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - platformChannel:     - Platform channel, supports the following parameters:     - _1: Douyin Video     - _10: Douyin Live ### Return: - kol Service Price  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; platformChannel &#x3D; \&quot;_1\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolServicePriceV1ApiV1DouyinXingtuKolServicePriceV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //String platformChannel = null;
        //
        //ResponseModel response = api.kolServicePriceV1ApiV1DouyinXingtuKolServicePriceV1Get_0(kolId, platformChannel);

        // TODO: test validations
    }
    /**
     * 获取kol连接用户来源V1/Get kol Touch Distribution V1
     *
     * # [中文] ### 用途: - 获取kol连接用户来源V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol连接用户来源  # [English] ### Purpose: - Get kol Touch Distribution V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Touch Distribution  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolTouchDistributionV1ApiV1DouyinXingtuKolTouchDistributionV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolTouchDistributionV1ApiV1DouyinXingtuKolTouchDistributionV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol连接用户来源V1/Get kol Touch Distribution V1
     *
     * # [中文] ### 用途: - 获取kol连接用户来源V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol连接用户来源  # [English] ### Purpose: - Get kol Touch Distribution V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Touch Distribution  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolTouchDistributionV1ApiV1DouyinXingtuKolTouchDistributionV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolTouchDistributionV1ApiV1DouyinXingtuKolTouchDistributionV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol视频表现V1/Get kol Video Performance V1
     *
     * # [中文] ### 用途: - 获取kol视频表现V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - onlyAssign: 是否只显示分配作品，具体参数如下:     - false : 显示全部，包括个人作品和分配作品，默认值。     - true : 只显示来自星图的分配作品。 ### 返回: - kol视频表现  # [English] ### Purpose: - Get kol Video Performance V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - onlyAssign: Whether to display only assigned works, the specific parameters are as follows:     - false : Show all, including personal works and assigned works, default value.     - true : Only display assigned works from XingTu. ### Return: - kol Video Performance  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; onlyAssign &#x3D; False
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolVideoPerformanceV1ApiV1DouyinXingtuKolVideoPerformanceV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //Boolean onlyAssign = null;
        //
        //ResponseModel response = api.kolVideoPerformanceV1ApiV1DouyinXingtuKolVideoPerformanceV1Get(kolId, onlyAssign);

        // TODO: test validations
    }
    /**
     * 获取kol视频表现V1/Get kol Video Performance V1
     *
     * # [中文] ### 用途: - 获取kol视频表现V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - onlyAssign: 是否只显示分配作品，具体参数如下:     - false : 显示全部，包括个人作品和分配作品，默认值。     - true : 只显示来自星图的分配作品。 ### 返回: - kol视频表现  # [English] ### Purpose: - Get kol Video Performance V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; - onlyAssign: Whether to display only assigned works, the specific parameters are as follows:     - false : Show all, including personal works and assigned works, default value.     - true : Only display assigned works from XingTu. ### Return: - kol Video Performance  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot; onlyAssign &#x3D; False
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolVideoPerformanceV1ApiV1DouyinXingtuKolVideoPerformanceV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //Boolean onlyAssign = null;
        //
        //ResponseModel response = api.kolVideoPerformanceV1ApiV1DouyinXingtuKolVideoPerformanceV1Get_0(kolId, onlyAssign);

        // TODO: test validations
    }
    /**
     * 获取kol星图指数V1/Get kol Xingtu Index V1
     *
     * # [中文] ### 用途: - 获取kol星图指数V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol星图指数  # [English] ### Purpose: - Get kol Xingtu Index V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Xingtu Index  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolXingtuIndexV1ApiV1DouyinXingtuKolXingtuIndexV1GetTest() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolXingtuIndexV1ApiV1DouyinXingtuKolXingtuIndexV1Get(kolId);

        // TODO: test validations
    }
    /**
     * 获取kol星图指数V1/Get kol Xingtu Index V1
     *
     * # [中文] ### 用途: - 获取kol星图指数V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - kolId: 用户的kolId, 可以从接口以下接口获取：     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### 返回: - kol星图指数  # [English] ### Purpose: - Get kol Xingtu Index V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - kolId: User kolId, can be obtained from the following interfaces:     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id&#x60;     - &#x60;/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id&#x60; ### Return: - kol Xingtu Index  # [示例/Example] kolId &#x3D; \&quot;7048929565493690398\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kolXingtuIndexV1ApiV1DouyinXingtuKolXingtuIndexV1Get_0Test() throws ApiException {
        //
        //String kolId = null;
        //
        //ResponseModel response = api.kolXingtuIndexV1ApiV1DouyinXingtuKolXingtuIndexV1Get_0(kolId);

        // TODO: test validations
    }
    /**
     * 关键词搜索kol V1/Search Kol V1
     *
     * # [中文] ### 用途: - 关键词搜索kol V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - keyword: 关键词 - platformSource:     - 平台来源，支持以下参数:     - _1 :抖音(douyin)     - _2 :头条(toutiao)     - _3 :西瓜(xigua) - page: 页码，从1开始 ### 返回: - kol列表  # [English] ### Purpose: - Search Kol V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - keyword: Keyword - platformSource:     - Platform source, supports the following parameters:     - _1 :Douyin     - _2 :Toutiao     - _3 :Xigua - page: Page number, starting from 1 ### Return: - Kol List  # [示例/Example] keyword &#x3D; \&quot;人工智能\&quot; platformSource &#x3D; \&quot;_1\&quot; page &#x3D; 1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchKolV1ApiV1DouyinXingtuSearchKolV1GetTest() throws ApiException {
        //
        //String keyword = null;
        //
        //String platformSource = null;
        //
        //Integer page = null;
        //
        //ResponseModel response = api.searchKolV1ApiV1DouyinXingtuSearchKolV1Get(keyword, platformSource, page);

        // TODO: test validations
    }
    /**
     * 关键词搜索kol V1/Search Kol V1
     *
     * # [中文] ### 用途: - 关键词搜索kol V1 - 该接口数据使用企业账号进行请求，收费较贵。 - 价格：0.02$ / 次 ### 参数: - keyword: 关键词 - platformSource:     - 平台来源，支持以下参数:     - _1 :抖音(douyin)     - _2 :头条(toutiao)     - _3 :西瓜(xigua) - page: 页码，从1开始 ### 返回: - kol列表  # [English] ### Purpose: - Search Kol V1 - The interface data is requested using an enterprise account, which is more expensive. - Price: 0.02$ / time ### Parameters: - keyword: Keyword - platformSource:     - Platform source, supports the following parameters:     - _1 :Douyin     - _2 :Toutiao     - _3 :Xigua - page: Page number, starting from 1 ### Return: - Kol List  # [示例/Example] keyword &#x3D; \&quot;人工智能\&quot; platformSource &#x3D; \&quot;_1\&quot; page &#x3D; 1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchKolV1ApiV1DouyinXingtuSearchKolV1Get_0Test() throws ApiException {
        //
        //String keyword = null;
        //
        //String platformSource = null;
        //
        //Integer page = null;
        //
        //ResponseModel response = api.searchKolV1ApiV1DouyinXingtuSearchKolV1Get_0(keyword, platformSource, page);

        // TODO: test validations
    }
}
