/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tikhub.client.api;

import io.tikhub.client.ApiException;
import org.openapitools.client.model.HttpValidationError;
import org.openapitools.client.model.ResponseModel;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ToutiaoAppApiApi
 */
public class ToutiaoAppApiApiTest {

    private final ToutiaoAppApiApi api = new ToutiaoAppApiApi();

    /**
     * 获取指定文章的信息/Get information of specified article
     *
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id &#x3D; \&quot;7450114952884503059\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getArticleInfoApiV1ToutiaoAppGetArticleInfoGetTest() throws ApiException {
        //
        //String groupId = null;
        //
        //ResponseModel response = api.getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(groupId);

        // TODO: test validations
    }
    /**
     * 获取指定文章的信息/Get information of specified article
     *
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id &#x3D; \&quot;7450114952884503059\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_0Test() throws ApiException {
        //
        //String groupId = null;
        //
        //ResponseModel response = api.getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_0(groupId);

        // TODO: test validations
    }
    /**
     * 获取指定作品的评论/Get comments of specified post
     *
     * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id &#x3D; \&quot;7453372680222523931\&quot; offset &#x3D; \&quot;0\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommentsApiV1ToutiaoAppGetCommentsGetTest() throws ApiException {
        //
        //String groupId = null;
        //
        //String offset = null;
        //
        //ResponseModel response = api.getCommentsApiV1ToutiaoAppGetCommentsGet(groupId, offset);

        // TODO: test validations
    }
    /**
     * 获取指定作品的评论/Get comments of specified post
     *
     * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id &#x3D; \&quot;7453372680222523931\&quot; offset &#x3D; \&quot;0\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommentsApiV1ToutiaoAppGetCommentsGet_0Test() throws ApiException {
        //
        //String groupId = null;
        //
        //String offset = null;
        //
        //ResponseModel response = api.getCommentsApiV1ToutiaoAppGetCommentsGet_0(groupId, offset);

        // TODO: test validations
    }
    /**
     * 从头条用户主页获取用户user_id/Get user_id from user profile
     *
     * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url &#x3D; \&quot;https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserIdApiV1ToutiaoAppGetUserIdGetTest() throws ApiException {
        //
        //String userProfileUrl = null;
        //
        //ResponseModel response = api.getUserIdApiV1ToutiaoAppGetUserIdGet(userProfileUrl);

        // TODO: test validations
    }
    /**
     * 从头条用户主页获取用户user_id/Get user_id from user profile
     *
     * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url &#x3D; \&quot;https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserIdApiV1ToutiaoAppGetUserIdGet_0Test() throws ApiException {
        //
        //String userProfileUrl = null;
        //
        //ResponseModel response = api.getUserIdApiV1ToutiaoAppGetUserIdGet_0(userProfileUrl);

        // TODO: test validations
    }
    /**
     * 获取指定用户的信息/Get information of specified user
     *
     * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - &#x60;/api/v1/toutiao/app/get_user_id&#x60; ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - &#x60;/api/v1/toutiao/app/get_user_id&#x60; ### Return: - User information  # [示例/Example] user_id &#x3D; \&quot;1352838578180211\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserInfoApiV1ToutiaoAppGetUserInfoGetTest() throws ApiException {
        //
        //String userId = null;
        //
        //ResponseModel response = api.getUserInfoApiV1ToutiaoAppGetUserInfoGet(userId);

        // TODO: test validations
    }
    /**
     * 获取指定用户的信息/Get information of specified user
     *
     * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - &#x60;/api/v1/toutiao/app/get_user_id&#x60; ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - &#x60;/api/v1/toutiao/app/get_user_id&#x60; ### Return: - User information  # [示例/Example] user_id &#x3D; \&quot;1352838578180211\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserInfoApiV1ToutiaoAppGetUserInfoGet_0Test() throws ApiException {
        //
        //String userId = null;
        //
        //ResponseModel response = api.getUserInfoApiV1ToutiaoAppGetUserInfoGet_0(userId);

        // TODO: test validations
    }
    /**
     * 获取指定视频的信息/Get information of specified video
     *
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id &#x3D; \&quot;7431543350882206242\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVideoInfoApiV1ToutiaoAppGetVideoInfoGetTest() throws ApiException {
        //
        //String groupId = null;
        //
        //ResponseModel response = api.getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(groupId);

        // TODO: test validations
    }
    /**
     * 获取指定视频的信息/Get information of specified video
     *
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id &#x3D; \&quot;7431543350882206242\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_0Test() throws ApiException {
        //
        //String groupId = null;
        //
        //ResponseModel response = api.getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_0(groupId);

        // TODO: test validations
    }
}
