/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tikhub.client.api;

import io.tikhub.client.ApiException;
import org.openapitools.client.model.HttpValidationError;
import org.openapitools.client.model.ResponseModel;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TwitterWebApiApi
 */
public class TwitterWebApiApiTest {

    private final TwitterWebApiApi api = new TwitterWebApiApi();

    /**
     * 获取最新的推文评论/Get the latest tweet comments
     *
     * # [中文] ### 用途: - 获取最新的推文评论 ### 参数: - tweet_id: 推文ID - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 推文评论  # [English] ### Purpose: - Get the latest tweet comments ### Parameters: - tweet_id: Tweet ID - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - Tweet comments  # [示例/Example] tweet_id &#x3D; \&quot;1808168603721650364\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchLatestPostCommentsApiV1TwitterWebFetchLatestPostCommentsGetTest() throws ApiException {
        //
        //String tweetId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchLatestPostCommentsApiV1TwitterWebFetchLatestPostCommentsGet(tweetId, cursor);

        // TODO: test validations
    }
    /**
     * 获取最新的推文评论/Get the latest tweet comments
     *
     * # [中文] ### 用途: - 获取最新的推文评论 ### 参数: - tweet_id: 推文ID - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 推文评论  # [English] ### Purpose: - Get the latest tweet comments ### Parameters: - tweet_id: Tweet ID - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - Tweet comments  # [示例/Example] tweet_id &#x3D; \&quot;1808168603721650364\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchLatestPostCommentsApiV1TwitterWebFetchLatestPostCommentsGet_0Test() throws ApiException {
        //
        //String tweetId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchLatestPostCommentsApiV1TwitterWebFetchLatestPostCommentsGet_0(tweetId, cursor);

        // TODO: test validations
    }
    /**
     * 获取评论/Get comments
     *
     * # [中文] ### 用途: - 获取推文下的评论 ### 参数: - tweet_id: 推文ID - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 评论  # [English] ### Purpose: - Get comments under the tweet ### Parameters: - tweet_id: Tweet ID - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - Comments  # [示例/Example] tweet_id &#x3D; \&quot;1808168603721650364\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchPostCommentsApiV1TwitterWebFetchPostCommentsGetTest() throws ApiException {
        //
        //String tweetId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchPostCommentsApiV1TwitterWebFetchPostCommentsGet(tweetId, cursor);

        // TODO: test validations
    }
    /**
     * 获取评论/Get comments
     *
     * # [中文] ### 用途: - 获取推文下的评论 ### 参数: - tweet_id: 推文ID - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 评论  # [English] ### Purpose: - Get comments under the tweet ### Parameters: - tweet_id: Tweet ID - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - Comments  # [示例/Example] tweet_id &#x3D; \&quot;1808168603721650364\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchPostCommentsApiV1TwitterWebFetchPostCommentsGet_0Test() throws ApiException {
        //
        //String tweetId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchPostCommentsApiV1TwitterWebFetchPostCommentsGet_0(tweetId, cursor);

        // TODO: test validations
    }
    /**
     * 转推用户列表/ReTweet User list
     *
     * # [中文] ### 用途: - 获取转推用户列表 ### 参数: - tweet_id: 推文ID，可以从推文链接中获取。例如：https://x.com/elonmusk/status/1808168603721650364 中的 1808168603721650364。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 转推用户列表  # [English] ### Purpose: - Get ReTweet User list ### Parameters: - tweet_id: Tweet ID, can be obtained from the tweet link. For example: 1808168603721650364 in https://x.com/elonmusk/status/1808168603721650364 - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - ReTweet User list  # [示例/Example] tweet_id &#x3D; \&quot;1808168603721650364\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchRetweetUserListApiV1TwitterWebFetchRetweetUserListGetTest() throws ApiException {
        //
        //String tweetId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchRetweetUserListApiV1TwitterWebFetchRetweetUserListGet(tweetId, cursor);

        // TODO: test validations
    }
    /**
     * 转推用户列表/ReTweet User list
     *
     * # [中文] ### 用途: - 获取转推用户列表 ### 参数: - tweet_id: 推文ID，可以从推文链接中获取。例如：https://x.com/elonmusk/status/1808168603721650364 中的 1808168603721650364。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 转推用户列表  # [English] ### Purpose: - Get ReTweet User list ### Parameters: - tweet_id: Tweet ID, can be obtained from the tweet link. For example: 1808168603721650364 in https://x.com/elonmusk/status/1808168603721650364 - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - ReTweet User list  # [示例/Example] tweet_id &#x3D; \&quot;1808168603721650364\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchRetweetUserListApiV1TwitterWebFetchRetweetUserListGet_0Test() throws ApiException {
        //
        //String tweetId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchRetweetUserListApiV1TwitterWebFetchRetweetUserListGet_0(tweetId, cursor);

        // TODO: test validations
    }
    /**
     * 搜索/Search
     *
     * # [中文] ### 用途: - 搜索 ### 参数: - keyword: 搜索关键字 - search_type: 搜索类型，默认为Top，其他可选值为Latest，Media，People, Lists - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 搜索结果  # [English] ### Purpose: - Search ### Parameters: - keyword: Search keyword - search_type: Search type, default is Top, other optional values are Latest, Media, People, Lists - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - Search results  # [示例/Example] keyword &#x3D; \&quot;Elon Musk\&quot; search_type &#x3D; \&quot;Top\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchSearchTimelineApiV1TwitterWebFetchSearchTimelineGetTest() throws ApiException {
        //
        //String keyword = null;
        //
        //String searchType = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchSearchTimelineApiV1TwitterWebFetchSearchTimelineGet(keyword, searchType, cursor);

        // TODO: test validations
    }
    /**
     * 搜索/Search
     *
     * # [中文] ### 用途: - 搜索 ### 参数: - keyword: 搜索关键字 - search_type: 搜索类型，默认为Top，其他可选值为Latest，Media，People, Lists - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 搜索结果  # [English] ### Purpose: - Search ### Parameters: - keyword: Search keyword - search_type: Search type, default is Top, other optional values are Latest, Media, People, Lists - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - Search results  # [示例/Example] keyword &#x3D; \&quot;Elon Musk\&quot; search_type &#x3D; \&quot;Top\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchSearchTimelineApiV1TwitterWebFetchSearchTimelineGet_0Test() throws ApiException {
        //
        //String keyword = null;
        //
        //String searchType = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchSearchTimelineApiV1TwitterWebFetchSearchTimelineGet_0(keyword, searchType, cursor);

        // TODO: test validations
    }
    /**
     * 趋势/Trending
     *
     * # [中文] ### 用途: - 获取趋势 ### 参数: - country: 国家，默认为UnitedStates，其他可选值见下方     - China     - India     - Japan     - Russia     - Germany     - Indonesia     - Brazil     - France     - UnitedKingdom     - Turkey     - Italy     - Mexico     - SouthKorea     - Canada     - Spain     - SaudiArabia     - Egypt     - Australia     - Poland     - Iran     - Pakistan     - Vietnam     - Nigeria     - Bangladesh     - Netherlands     - Argentina     - Philippines     - Malaysia     - Colombia     - UniteArabEmirates     - Romania     - Belgium     - Switzerland     - Singapore     - Sweden     - Norway     - Austria     - Kazakhstan     - Algeria     - Chile     - Czechia     - Peru     - Iraq     - Israel     - Ukraine     - Denmark     - Portugal     - Hungary     - Greece     - Finland     - NewZealand     - Belarus     - Slovakia     - Serbia     - Lithuania     - Luxembourg     - Estonia  ### 返回: - 趋势  # [English] ### Purpose: - Get Trending ### Parameters: - country: Country, default is UnitedStates, other optional values are as follows     - China     - India     - Japan     - Russia     - Germany     - Indonesia     - Brazil     - France     - UnitedKingdom     - Turkey     - Italy     - Mexico     - SouthKorea     - Canada     - Spain     - SaudiArabia     - Egypt     - Australia     - Poland     - Iran     - Pakistan     - Vietnam     - Nigeria     - Bangladesh     - Netherlands     - Argentina     - Philippines     - Malaysia     - Colombia     - UniteArabEmirates     - Romania     - Belgium     - Switzerland     - Singapore     - Sweden     - Norway     - Austria     - Kazakhstan     - Algeria     - Chile     - Czechia     - Peru  ### Return: - Trending  # [示例/Example] country &#x3D; \&quot;UnitedStates\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchTrendingApiV1TwitterWebFetchTrendingGetTest() throws ApiException {
        //
        //String country = null;
        //
        //ResponseModel response = api.fetchTrendingApiV1TwitterWebFetchTrendingGet(country);

        // TODO: test validations
    }
    /**
     * 趋势/Trending
     *
     * # [中文] ### 用途: - 获取趋势 ### 参数: - country: 国家，默认为UnitedStates，其他可选值见下方     - China     - India     - Japan     - Russia     - Germany     - Indonesia     - Brazil     - France     - UnitedKingdom     - Turkey     - Italy     - Mexico     - SouthKorea     - Canada     - Spain     - SaudiArabia     - Egypt     - Australia     - Poland     - Iran     - Pakistan     - Vietnam     - Nigeria     - Bangladesh     - Netherlands     - Argentina     - Philippines     - Malaysia     - Colombia     - UniteArabEmirates     - Romania     - Belgium     - Switzerland     - Singapore     - Sweden     - Norway     - Austria     - Kazakhstan     - Algeria     - Chile     - Czechia     - Peru     - Iraq     - Israel     - Ukraine     - Denmark     - Portugal     - Hungary     - Greece     - Finland     - NewZealand     - Belarus     - Slovakia     - Serbia     - Lithuania     - Luxembourg     - Estonia  ### 返回: - 趋势  # [English] ### Purpose: - Get Trending ### Parameters: - country: Country, default is UnitedStates, other optional values are as follows     - China     - India     - Japan     - Russia     - Germany     - Indonesia     - Brazil     - France     - UnitedKingdom     - Turkey     - Italy     - Mexico     - SouthKorea     - Canada     - Spain     - SaudiArabia     - Egypt     - Australia     - Poland     - Iran     - Pakistan     - Vietnam     - Nigeria     - Bangladesh     - Netherlands     - Argentina     - Philippines     - Malaysia     - Colombia     - UniteArabEmirates     - Romania     - Belgium     - Switzerland     - Singapore     - Sweden     - Norway     - Austria     - Kazakhstan     - Algeria     - Chile     - Czechia     - Peru  ### Return: - Trending  # [示例/Example] country &#x3D; \&quot;UnitedStates\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchTrendingApiV1TwitterWebFetchTrendingGet_0Test() throws ApiException {
        //
        //String country = null;
        //
        //ResponseModel response = api.fetchTrendingApiV1TwitterWebFetchTrendingGet_0(country);

        // TODO: test validations
    }
    /**
     * 获取单个推文数据/Get single tweet data
     *
     * # [中文] ### 用途: - 获取单个推文数据 ### 参数: - tweet_id: 推文ID，可以从推文链接中获取。例如：https://x.com/elonmusk/status/1808168603721650364 中的 1808168603721650364。 ### 返回: - 推文数据  # [English] ### Purpose: - Get single tweet data ### Parameters: - tweet_id: Tweet ID, can be obtained from the tweet link. For example: 1808168603721650364 in https://x.com/elonmusk/status/1808168603721650364 ### Return: - Tweet data  # [示例/Example] tweet_id &#x3D; \&quot;1808168603721650364\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchTweetDetailApiV1TwitterWebFetchTweetDetailGetTest() throws ApiException {
        //
        //String tweetId = null;
        //
        //ResponseModel response = api.fetchTweetDetailApiV1TwitterWebFetchTweetDetailGet(tweetId);

        // TODO: test validations
    }
    /**
     * 获取单个推文数据/Get single tweet data
     *
     * # [中文] ### 用途: - 获取单个推文数据 ### 参数: - tweet_id: 推文ID，可以从推文链接中获取。例如：https://x.com/elonmusk/status/1808168603721650364 中的 1808168603721650364。 ### 返回: - 推文数据  # [English] ### Purpose: - Get single tweet data ### Parameters: - tweet_id: Tweet ID, can be obtained from the tweet link. For example: 1808168603721650364 in https://x.com/elonmusk/status/1808168603721650364 ### Return: - Tweet data  # [示例/Example] tweet_id &#x3D; \&quot;1808168603721650364\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchTweetDetailApiV1TwitterWebFetchTweetDetailGet_0Test() throws ApiException {
        //
        //String tweetId = null;
        //
        //ResponseModel response = api.fetchTweetDetailApiV1TwitterWebFetchTweetDetailGet_0(tweetId);

        // TODO: test validations
    }
    /**
     * 用户粉丝/User Followers
     *
     * # [中文] ### 用途: - 获取用户粉丝 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 用户粉丝  # [English] ### Purpose: - Get User Followers ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - User Followers  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserFollowersApiV1TwitterWebFetchUserFollowersGetTest() throws ApiException {
        //
        //String screenName = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserFollowersApiV1TwitterWebFetchUserFollowersGet(screenName, cursor);

        // TODO: test validations
    }
    /**
     * 用户粉丝/User Followers
     *
     * # [中文] ### 用途: - 获取用户粉丝 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 用户粉丝  # [English] ### Purpose: - Get User Followers ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - User Followers  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserFollowersApiV1TwitterWebFetchUserFollowersGet_0Test() throws ApiException {
        //
        //String screenName = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserFollowersApiV1TwitterWebFetchUserFollowersGet_0(screenName, cursor);

        // TODO: test validations
    }
    /**
     * 用户关注/User Followings
     *
     * # [中文] ### 用途: - 获取用户关注 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 用户关注  # [English] ### Purpose: - Get User Followings ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - User Followings  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserFollowingsApiV1TwitterWebFetchUserFollowingsGetTest() throws ApiException {
        //
        //String screenName = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserFollowingsApiV1TwitterWebFetchUserFollowingsGet(screenName, cursor);

        // TODO: test validations
    }
    /**
     * 用户关注/User Followings
     *
     * # [中文] ### 用途: - 获取用户关注 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 用户关注  # [English] ### Purpose: - Get User Followings ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - User Followings  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserFollowingsApiV1TwitterWebFetchUserFollowingsGet_0Test() throws ApiException {
        //
        //String screenName = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserFollowingsApiV1TwitterWebFetchUserFollowingsGet_0(screenName, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户高光推文/Get user highlights tweets
     *
     * # [中文] ### 用途: - 获取用户高光推文 ### 参数: - userId: 用户ID - count: 数量，默认为20 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取     - JSONPath: $.data.data.user.result.timeline_v2.timeline.instructions.[1].entries.[-1].content.value ### 返回: - 用户高光推文  # [English] ### Purpose: - Get user highlights tweets ### Parameters: - userId: User ID - count: Count, default is 20 - cursor: Cursor, default is None, used for paging, obtained from the last request     - JSONPath: $.data.data.user.result.timeline_v2.timeline.instructions.[1].entries.[-1].content.value ### Return: - User highlights tweets  # [示例/Example] userId &#x3D; \&quot;44196397\&quot; count &#x3D; 20 cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserHighlightsTweetsApiV1TwitterWebFetchUserHighlightsTweetsGetTest() throws ApiException {
        //
        //String userId = null;
        //
        //Integer count = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserHighlightsTweetsApiV1TwitterWebFetchUserHighlightsTweetsGet(userId, count, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户高光推文/Get user highlights tweets
     *
     * # [中文] ### 用途: - 获取用户高光推文 ### 参数: - userId: 用户ID - count: 数量，默认为20 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取     - JSONPath: $.data.data.user.result.timeline_v2.timeline.instructions.[1].entries.[-1].content.value ### 返回: - 用户高光推文  # [English] ### Purpose: - Get user highlights tweets ### Parameters: - userId: User ID - count: Count, default is 20 - cursor: Cursor, default is None, used for paging, obtained from the last request     - JSONPath: $.data.data.user.result.timeline_v2.timeline.instructions.[1].entries.[-1].content.value ### Return: - User highlights tweets  # [示例/Example] userId &#x3D; \&quot;44196397\&quot; count &#x3D; 20 cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserHighlightsTweetsApiV1TwitterWebFetchUserHighlightsTweetsGet_0Test() throws ApiException {
        //
        //String userId = null;
        //
        //Integer count = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserHighlightsTweetsApiV1TwitterWebFetchUserHighlightsTweetsGet_0(userId, count, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户媒体/Get user media
     *
     * # [中文] ### 用途: - 获取用户媒体 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - rest_id: 用户ID，例如：44196397，如果使用用户ID则会忽略用户名，两者只能选其一。 ### 返回: - 用户媒体  # [English] ### Purpose: - Get user media ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - rest_id: User ID, for example: 44196397, if the user ID is used, the username will be ignored, only one of them can be selected. ### Return: - User media  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserMediaApiV1TwitterWebFetchUserMediaGetTest() throws ApiException {
        //
        //String screenName = null;
        //
        //Integer restId = null;
        //
        //ResponseModel response = api.fetchUserMediaApiV1TwitterWebFetchUserMediaGet(screenName, restId);

        // TODO: test validations
    }
    /**
     * 获取用户媒体/Get user media
     *
     * # [中文] ### 用途: - 获取用户媒体 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - rest_id: 用户ID，例如：44196397，如果使用用户ID则会忽略用户名，两者只能选其一。 ### 返回: - 用户媒体  # [English] ### Purpose: - Get user media ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - rest_id: User ID, for example: 44196397, if the user ID is used, the username will be ignored, only one of them can be selected. ### Return: - User media  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserMediaApiV1TwitterWebFetchUserMediaGet_0Test() throws ApiException {
        //
        //String screenName = null;
        //
        //Integer restId = null;
        //
        //ResponseModel response = api.fetchUserMediaApiV1TwitterWebFetchUserMediaGet_0(screenName, restId);

        // TODO: test validations
    }
    /**
     * 获取用户发帖/Get user post
     *
     * # [中文] ### 用途: - 获取用户发帖 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - rest_id: 用户ID，例如：44196397，如果使用用户ID则会忽略用户名，两者只能选其一。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中的JSON中获取。 ### 返回: - 用户发帖  # [English] ### Purpose: - Get user post ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - rest_id: User ID, for example: 44196397, if the user ID is used, the username will be ignored, only one of them can be selected. - cursor: Cursor, default is None, used for paging, obtained from the JSON in the last request.  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot; rest_id &#x3D; 44196397 cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserPostTweetApiV1TwitterWebFetchUserPostTweetGetTest() throws ApiException {
        //
        //String screenName = null;
        //
        //Integer restId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserPostTweetApiV1TwitterWebFetchUserPostTweetGet(screenName, restId, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户发帖/Get user post
     *
     * # [中文] ### 用途: - 获取用户发帖 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - rest_id: 用户ID，例如：44196397，如果使用用户ID则会忽略用户名，两者只能选其一。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中的JSON中获取。 ### 返回: - 用户发帖  # [English] ### Purpose: - Get user post ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - rest_id: User ID, for example: 44196397, if the user ID is used, the username will be ignored, only one of them can be selected. - cursor: Cursor, default is None, used for paging, obtained from the JSON in the last request.  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot; rest_id &#x3D; 44196397 cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserPostTweetApiV1TwitterWebFetchUserPostTweetGet_0Test() throws ApiException {
        //
        //String screenName = null;
        //
        //Integer restId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserPostTweetApiV1TwitterWebFetchUserPostTweetGet_0(screenName, restId, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户资料/Get user profile
     *
     * # [中文] ### 用途: - 获取用户资料 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - rest_id: 用户ID，例如：44196397，如果使用用户ID则会忽略用户名，两者只能选其一。 ### 返回: - 用户资料  # [English] ### Purpose: - Get user profile ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - rest_id: User ID, for example: 44196397, if the user ID is used, the username will be ignored, only one of them can be selected. ### Return: - User profile  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserProfileApiV1TwitterWebFetchUserProfileGetTest() throws ApiException {
        //
        //String screenName = null;
        //
        //Integer restId = null;
        //
        //ResponseModel response = api.fetchUserProfileApiV1TwitterWebFetchUserProfileGet(screenName, restId);

        // TODO: test validations
    }
    /**
     * 获取用户资料/Get user profile
     *
     * # [中文] ### 用途: - 获取用户资料 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - rest_id: 用户ID，例如：44196397，如果使用用户ID则会忽略用户名，两者只能选其一。 ### 返回: - 用户资料  # [English] ### Purpose: - Get user profile ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - rest_id: User ID, for example: 44196397, if the user ID is used, the username will be ignored, only one of them can be selected. ### Return: - User profile  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserProfileApiV1TwitterWebFetchUserProfileGet_0Test() throws ApiException {
        //
        //String screenName = null;
        //
        //Integer restId = null;
        //
        //ResponseModel response = api.fetchUserProfileApiV1TwitterWebFetchUserProfileGet_0(screenName, restId);

        // TODO: test validations
    }
    /**
     * 获取用户推文回复/Get user tweet replies
     *
     * # [中文] ### 用途: - 获取用户推文回复 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 用户推文回复  # [English] ### Purpose: - Get user tweet replies ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - User tweet replies  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserTweetRepliesApiV1TwitterWebFetchUserTweetRepliesGetTest() throws ApiException {
        //
        //String screenName = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserTweetRepliesApiV1TwitterWebFetchUserTweetRepliesGet(screenName, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户推文回复/Get user tweet replies
     *
     * # [中文] ### 用途: - 获取用户推文回复 ### 参数: - screen_name: 用户名，例如：elonmusk，可以从用户主页链接中获取，例如：https://twitter.com/elonmusk 中的 elonmusk。 - cursor: 游标，默认为None，用于翻页，后续从上一次请求的返回结果中获取 ### 返回: - 用户推文回复  # [English] ### Purpose: - Get user tweet replies ### Parameters: - screen_name: Screen Name, for example: elonmusk, can be obtained from the user&#39;s homepage link, for example: elonmusk in https://twitter.com/elonmusk - cursor: Cursor, default is None, used for paging, obtained from the last request ### Return: - User tweet replies  # [示例/Example] screen_name &#x3D; \&quot;elonmusk\&quot; cursor &#x3D; None
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserTweetRepliesApiV1TwitterWebFetchUserTweetRepliesGet_0Test() throws ApiException {
        //
        //String screenName = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchUserTweetRepliesApiV1TwitterWebFetchUserTweetRepliesGet_0(screenName, cursor);

        // TODO: test validations
    }
}
