/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tikhub.client.api;

import io.tikhub.client.ApiException;
import org.openapitools.client.model.HttpValidationError;
import org.openapitools.client.model.ResponseModel;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for XiaohongshuWebV2ApiApi
 */
public class XiaohongshuWebV2ApiApiTest {

    private final XiaohongshuWebV2ApiApi api = new XiaohongshuWebV2ApiApi();

    /**
     * 获取推荐笔记/Fetch feed notes
     *
     * # [中文] ### 用途: - 获取推荐笔记 ### 参数: - note_id: 笔记ID，可以从小红书的分享链接中获取 ### 返回: - 推荐笔记  # [English] ### Purpose: - Get feed notes ### Parameters: - note_id: Note ID, can be obtained from the sharing link of Xiaohongshu website. ### Return: - Feed notes  # [示例/Example] note_id &#x3D; \&quot;66c9cc31000000001f03a4bc\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchFeedNotesApiV1XiaohongshuWebV2FetchFeedNotesGetTest() throws ApiException {
        //
        //String noteId = null;
        //
        //ResponseModel response = api.fetchFeedNotesApiV1XiaohongshuWebV2FetchFeedNotesGet(noteId);

        // TODO: test validations
    }
    /**
     * 获取推荐笔记/Fetch feed notes
     *
     * # [中文] ### 用途: - 获取推荐笔记 ### 参数: - note_id: 笔记ID，可以从小红书的分享链接中获取 ### 返回: - 推荐笔记  # [English] ### Purpose: - Get feed notes ### Parameters: - note_id: Note ID, can be obtained from the sharing link of Xiaohongshu website. ### Return: - Feed notes  # [示例/Example] note_id &#x3D; \&quot;66c9cc31000000001f03a4bc\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchFeedNotesApiV1XiaohongshuWebV2FetchFeedNotesGet_0Test() throws ApiException {
        //
        //String noteId = null;
        //
        //ResponseModel response = api.fetchFeedNotesApiV1XiaohongshuWebV2FetchFeedNotesGet_0(noteId);

        // TODO: test validations
    }
    /**
     * 获取用户粉丝列表/Fetch follower list
     *
     * # [中文] ### 用途: - 获取用户粉丝列表 ### 参数: - user_id: 用户ID - cursor: 游标 ### 返回: - 用户粉丝列表  # [English] ### Purpose: - Get follower list ### Parameters: - user_id: User ID - cursor: Cursor ### Return: - Follower list  # [示例/Example] user_id &#x3D; \&quot;604a28420000000001005211\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchFollowerListApiV1XiaohongshuWebV2FetchFollowerListGetTest() throws ApiException {
        //
        //String userId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchFollowerListApiV1XiaohongshuWebV2FetchFollowerListGet(userId, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户粉丝列表/Fetch follower list
     *
     * # [中文] ### 用途: - 获取用户粉丝列表 ### 参数: - user_id: 用户ID - cursor: 游标 ### 返回: - 用户粉丝列表  # [English] ### Purpose: - Get follower list ### Parameters: - user_id: User ID - cursor: Cursor ### Return: - Follower list  # [示例/Example] user_id &#x3D; \&quot;604a28420000000001005211\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchFollowerListApiV1XiaohongshuWebV2FetchFollowerListGet_0Test() throws ApiException {
        //
        //String userId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchFollowerListApiV1XiaohongshuWebV2FetchFollowerListGet_0(userId, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户关注列表/Fetch following list
     *
     * # [中文] ### 用途: - 获取用户关注列表 ### 参数: - user_id: 用户ID - cursor: 游标 ### 返回: - 用户关注列表  # [English] ### Purpose: - Get following list ### Parameters: - user_id: User ID - cursor: Cursor ### Return: - Following list  # [示例/Example] user_id &#x3D; \&quot;604a28420000000001005211\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchFollowingListApiV1XiaohongshuWebV2FetchFollowingListGetTest() throws ApiException {
        //
        //String userId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchFollowingListApiV1XiaohongshuWebV2FetchFollowingListGet(userId, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户关注列表/Fetch following list
     *
     * # [中文] ### 用途: - 获取用户关注列表 ### 参数: - user_id: 用户ID - cursor: 游标 ### 返回: - 用户关注列表  # [English] ### Purpose: - Get following list ### Parameters: - user_id: User ID - cursor: Cursor ### Return: - Following list  # [示例/Example] user_id &#x3D; \&quot;604a28420000000001005211\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchFollowingListApiV1XiaohongshuWebV2FetchFollowingListGet_0Test() throws ApiException {
        //
        //String userId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchFollowingListApiV1XiaohongshuWebV2FetchFollowingListGet_0(userId, cursor);

        // TODO: test validations
    }
    /**
     * 获取主页笔记/Fetch home notes
     *
     * # [中文] ### 用途: - 获取主页笔记 ### 参数: - user_id: 用户ID - cursor: 游标 ### 返回: - 主页笔记  # [English] ### Purpose: - Get home notes ### Parameters: - user_id: User ID - cursor: Cursor ### Return: - Home notes  # [示例/Example] user_id &#x3D; \&quot;5f3e0d00000000001f03a4bc\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHomeNotesApiV1XiaohongshuWebV2FetchHomeNotesGetTest() throws ApiException {
        //
        //String userId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchHomeNotesApiV1XiaohongshuWebV2FetchHomeNotesGet(userId, cursor);

        // TODO: test validations
    }
    /**
     * 获取主页笔记/Fetch home notes
     *
     * # [中文] ### 用途: - 获取主页笔记 ### 参数: - user_id: 用户ID - cursor: 游标 ### 返回: - 主页笔记  # [English] ### Purpose: - Get home notes ### Parameters: - user_id: User ID - cursor: Cursor ### Return: - Home notes  # [示例/Example] user_id &#x3D; \&quot;5f3e0d00000000001f03a4bc\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHomeNotesApiV1XiaohongshuWebV2FetchHomeNotesGet_0Test() throws ApiException {
        //
        //String userId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchHomeNotesApiV1XiaohongshuWebV2FetchHomeNotesGet_0(userId, cursor);

        // TODO: test validations
    }
    /**
     * 获取笔记评论/Fetch note comments
     *
     * # [中文] ### 用途: - 获取笔记评论 ### 参数: - note_id: 笔记ID - cursor: 游标 ### 返回: - 笔记评论  # [English] ### Purpose: - Get note comments ### Parameters: - note_id: Note ID - cursor: Cursor ### Return: - Note comments  # [示例/Example] note_id &#x3D; \&quot;651ccaa9000000001f03d7f7\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchNoteCommentsApiV1XiaohongshuWebV2FetchNoteCommentsGetTest() throws ApiException {
        //
        //String noteId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchNoteCommentsApiV1XiaohongshuWebV2FetchNoteCommentsGet(noteId, cursor);

        // TODO: test validations
    }
    /**
     * 获取笔记评论/Fetch note comments
     *
     * # [中文] ### 用途: - 获取笔记评论 ### 参数: - note_id: 笔记ID - cursor: 游标 ### 返回: - 笔记评论  # [English] ### Purpose: - Get note comments ### Parameters: - note_id: Note ID - cursor: Cursor ### Return: - Note comments  # [示例/Example] note_id &#x3D; \&quot;651ccaa9000000001f03d7f7\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchNoteCommentsApiV1XiaohongshuWebV2FetchNoteCommentsGet_0Test() throws ApiException {
        //
        //String noteId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchNoteCommentsApiV1XiaohongshuWebV2FetchNoteCommentsGet_0(noteId, cursor);

        // TODO: test validations
    }
    /**
     * 获取搜索笔记/Fetch search notes
     *
     * # [中文] ### 用途: - 获取搜索笔记 ### 参数: - keywords：搜索关键词 - sort_type：排序方式     - general：综合     - time_descending：最新     - popularity_descending：最热 - note_type: 笔记类型     - 0：全部     - 1：视频     - 2：图文 ### 返回: - 搜索笔记  # [English] ### Purpose: - Get search notes ### Parameters: - keywords: Search keywords - sort_type: Sort type     - general: General     - time_descending: Latest     - popularity_descending: Popular - note_type: Note type     - 0: All     - 1: Video     - 2: Note ### Return: - Search notes  # [示例/Example] keywords &#x3D; \&quot;口红\&quot; page &#x3D; 1 sort_type &#x3D; \&quot;general\&quot; note_type &#x3D; \&quot;1\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchSearchNotesApiV1XiaohongshuWebV2FetchSearchNotesGetTest() throws ApiException {
        //
        //String keywords = null;
        //
        //Integer page = null;
        //
        //String sortType = null;
        //
        //String noteType = null;
        //
        //ResponseModel response = api.fetchSearchNotesApiV1XiaohongshuWebV2FetchSearchNotesGet(keywords, page, sortType, noteType);

        // TODO: test validations
    }
    /**
     * 获取搜索笔记/Fetch search notes
     *
     * # [中文] ### 用途: - 获取搜索笔记 ### 参数: - keywords：搜索关键词 - sort_type：排序方式     - general：综合     - time_descending：最新     - popularity_descending：最热 - note_type: 笔记类型     - 0：全部     - 1：视频     - 2：图文 ### 返回: - 搜索笔记  # [English] ### Purpose: - Get search notes ### Parameters: - keywords: Search keywords - sort_type: Sort type     - general: General     - time_descending: Latest     - popularity_descending: Popular - note_type: Note type     - 0: All     - 1: Video     - 2: Note ### Return: - Search notes  # [示例/Example] keywords &#x3D; \&quot;口红\&quot; page &#x3D; 1 sort_type &#x3D; \&quot;general\&quot; note_type &#x3D; \&quot;1\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchSearchNotesApiV1XiaohongshuWebV2FetchSearchNotesGet_0Test() throws ApiException {
        //
        //String keywords = null;
        //
        //Integer page = null;
        //
        //String sortType = null;
        //
        //String noteType = null;
        //
        //ResponseModel response = api.fetchSearchNotesApiV1XiaohongshuWebV2FetchSearchNotesGet_0(keywords, page, sortType, noteType);

        // TODO: test validations
    }
    /**
     * 获取子评论/Fetch sub comments
     *
     * # [中文] ### 用途: - 获取子评论 ### 参数: - note_id: 笔记ID - comment_id: 评论ID - cursor: 游标 ### 返回: - 子评论  # [English] ### Purpose: - Get sub comments ### Parameters: - note_id: Note ID - comment_id: Comment ID - cursor: Cursor ### Return: - Sub comments  # [示例/Example] note_id &#x3D; \&quot;673c894c0000000007033f92\&quot; comment_id &#x3D; \&quot;673ecdfc000000001503bf8b\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchSubCommentsApiV1XiaohongshuWebV2FetchSubCommentsGetTest() throws ApiException {
        //
        //String noteId = null;
        //
        //String commentId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchSubCommentsApiV1XiaohongshuWebV2FetchSubCommentsGet(noteId, commentId, cursor);

        // TODO: test validations
    }
    /**
     * 获取子评论/Fetch sub comments
     *
     * # [中文] ### 用途: - 获取子评论 ### 参数: - note_id: 笔记ID - comment_id: 评论ID - cursor: 游标 ### 返回: - 子评论  # [English] ### Purpose: - Get sub comments ### Parameters: - note_id: Note ID - comment_id: Comment ID - cursor: Cursor ### Return: - Sub comments  # [示例/Example] note_id &#x3D; \&quot;673c894c0000000007033f92\&quot; comment_id &#x3D; \&quot;673ecdfc000000001503bf8b\&quot; cursor &#x3D; \&quot;\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchSubCommentsApiV1XiaohongshuWebV2FetchSubCommentsGet_0Test() throws ApiException {
        //
        //String noteId = null;
        //
        //String commentId = null;
        //
        //String cursor = null;
        //
        //ResponseModel response = api.fetchSubCommentsApiV1XiaohongshuWebV2FetchSubCommentsGet_0(noteId, commentId, cursor);

        // TODO: test validations
    }
    /**
     * 获取用户信息/Fetch user info
     *
     * # [中文] ### 用途: - 获取用户信息 ### 参数: - user_id: 用户ID ### 返回: - 用户信息  # [English] ### Purpose: - Get user info ### Parameters: - user_id: User ID ### Return: - User info  # [示例/Example] user_id &#x3D; \&quot;5e3a8ee700000000010070c6\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserInfoApiV1XiaohongshuWebV2FetchUserInfoGetTest() throws ApiException {
        //
        //String userId = null;
        //
        //ResponseModel response = api.fetchUserInfoApiV1XiaohongshuWebV2FetchUserInfoGet(userId);

        // TODO: test validations
    }
    /**
     * 获取用户信息/Fetch user info
     *
     * # [中文] ### 用途: - 获取用户信息 ### 参数: - user_id: 用户ID ### 返回: - 用户信息  # [English] ### Purpose: - Get user info ### Parameters: - user_id: User ID ### Return: - User info  # [示例/Example] user_id &#x3D; \&quot;5e3a8ee700000000010070c6\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserInfoApiV1XiaohongshuWebV2FetchUserInfoGet_0Test() throws ApiException {
        //
        //String userId = null;
        //
        //ResponseModel response = api.fetchUserInfoApiV1XiaohongshuWebV2FetchUserInfoGet_0(userId);

        // TODO: test validations
    }
}
