/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BodyCloudflareTurnstileApiV1CaptchaCloudflareTurnstilePost
 */
public class BodyCloudflareTurnstileApiV1CaptchaCloudflareTurnstilePostTest {
    private final BodyCloudflareTurnstileApiV1CaptchaCloudflareTurnstilePost model = new BodyCloudflareTurnstileApiV1CaptchaCloudflareTurnstilePost();

    /**
     * Model tests for BodyCloudflareTurnstileApiV1CaptchaCloudflareTurnstilePost
     */
    @Test
    public void testBodyCloudflareTurnstileApiV1CaptchaCloudflareTurnstilePost() {
        // TODO: test BodyCloudflareTurnstileApiV1CaptchaCloudflareTurnstilePost
    }

    /**
     * Test the property 'sitekey'
     */
    @Test
    public void sitekeyTest() {
        // TODO: test sitekey
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'proxy'
     */
    @Test
    public void proxyTest() {
        // TODO: test proxy
    }

}
