/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost
 */
public class BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPostTest {
    private final BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost model = new BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost();

    /**
     * Model tests for BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost
     */
    @Test
    public void testBodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost() {
        // TODO: test BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'cookie'
     */
    @Test
    public void cookieTest() {
        // TODO: test cookie
    }

}
