/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost
 */
public class BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPostTest {
    private final BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost model = new BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost();

    /**
     * Model tests for BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost
     */
    @Test
    public void testBodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost() {
        // TODO: test BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'proxy'
     */
    @Test
    public void proxyTest() {
        // TODO: test proxy
    }

}
