/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TikTokAppV3ContentTranslate
 */
public class TikTokAppV3ContentTranslateTest {
    private final TikTokAppV3ContentTranslate model = new TikTokAppV3ContentTranslate();

    /**
     * Model tests for TikTokAppV3ContentTranslate
     */
    @Test
    public void testTikTokAppV3ContentTranslate() {
        // TODO: test TikTokAppV3ContentTranslate
    }

    /**
     * Test the property 'trgLang'
     */
    @Test
    public void trgLangTest() {
        // TODO: test trgLang
    }

    /**
     * Test the property 'srcContent'
     */
    @Test
    public void srcContentTest() {
        // TODO: test srcContent
    }

}
