/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Body_hcaptcha_api_v1_captcha_hcaptcha_post
 */
@ApiModel(description = "Body_hcaptcha_api_v1_captcha_hcaptcha_post")
@JsonPropertyOrder({
  BodyHcaptchaApiV1CaptchaHcaptchaPost.JSON_PROPERTY_SITEKEY,
  BodyHcaptchaApiV1CaptchaHcaptchaPost.JSON_PROPERTY_URL,
  BodyHcaptchaApiV1CaptchaHcaptchaPost.JSON_PROPERTY_PROXY
})

public class BodyHcaptchaApiV1CaptchaHcaptchaPost implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SITEKEY = "sitekey";
  private String sitekey;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_PROXY = "proxy";
  private Object proxy;


  public BodyHcaptchaApiV1CaptchaHcaptchaPost sitekey(String sitekey) {
    
    this.sitekey = sitekey;
    return this;
  }

   /**
   * Sitekey，Sitekey
   * @return sitekey
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Sitekey，Sitekey")
  @JsonProperty(JSON_PROPERTY_SITEKEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSitekey() {
    return sitekey;
  }


  public void setSitekey(String sitekey) {
    this.sitekey = sitekey;
  }


  public BodyHcaptchaApiV1CaptchaHcaptchaPost url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Url，URL
   * @return url
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Url，URL")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public BodyHcaptchaApiV1CaptchaHcaptchaPost proxy(Object proxy) {
    
    this.proxy = proxy;
    return this;
  }

   /**
   * Proxy，Proxy
   * @return proxy
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "Proxy，Proxy")
  @JsonProperty(JSON_PROPERTY_PROXY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getProxy() {
    return proxy;
  }


  public void setProxy(Object proxy) {
    this.proxy = proxy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyHcaptchaApiV1CaptchaHcaptchaPost bodyHcaptchaApiV1CaptchaHcaptchaPost = (BodyHcaptchaApiV1CaptchaHcaptchaPost) o;
    return Objects.equals(this.sitekey, bodyHcaptchaApiV1CaptchaHcaptchaPost.sitekey) &&
        Objects.equals(this.url, bodyHcaptchaApiV1CaptchaHcaptchaPost.url) &&
        Objects.equals(this.proxy, bodyHcaptchaApiV1CaptchaHcaptchaPost.proxy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sitekey, url, proxy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyHcaptchaApiV1CaptchaHcaptchaPost {\n");
    sb.append("    sitekey: ").append(toIndentedString(sitekey)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    proxy: ").append(toIndentedString(proxy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

