/*
 * Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body_recaptcha_v3_api_v1_captcha_recaptcha_v3_post
 */
@ApiModel(description = "Body_recaptcha_v3_api_v1_captcha_recaptcha_v3_post")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-19T06:19:02.654880600-07:00[America/Los_Angeles]")
public class BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post {
  public static final String SERIALIZED_NAME_SITEKEY = "sitekey";
  @SerializedName(SERIALIZED_NAME_SITEKEY)
  private String sitekey;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private String action;

  public static final String SERIALIZED_NAME_PROXY = "proxy";
  @SerializedName(SERIALIZED_NAME_PROXY)
  private Object proxy;


  public BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post sitekey(String sitekey) {
    
    this.sitekey = sitekey;
    return this;
  }

   /**
   * Sitekey，Sitekey
   * @return sitekey
  **/
  @ApiModelProperty(required = true, value = "Sitekey，Sitekey")

  public String getSitekey() {
    return sitekey;
  }


  public void setSitekey(String sitekey) {
    this.sitekey = sitekey;
  }


  public BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Url，URL
   * @return url
  **/
  @ApiModelProperty(required = true, value = "Url，URL")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * Action，Action
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Action，Action")

  public String getAction() {
    return action;
  }


  public void setAction(String action) {
    this.action = action;
  }


  public BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post proxy(Object proxy) {
    
    this.proxy = proxy;
    return this;
  }

   /**
   * Proxy，Proxy
   * @return proxy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Proxy，Proxy")

  public Object getProxy() {
    return proxy;
  }


  public void setProxy(Object proxy) {
    this.proxy = proxy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post bodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post = (BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post) o;
    return Objects.equals(this.sitekey, bodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post.sitekey) &&
        Objects.equals(this.url, bodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post.url) &&
        Objects.equals(this.action, bodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post.action) &&
        Objects.equals(this.proxy, bodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post.proxy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sitekey, url, action, proxy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post {\n");
    sb.append("    sitekey: ").append(toIndentedString(sitekey)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    proxy: ").append(toIndentedString(proxy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

