/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * iOS_Shortcut
 */
@ApiModel(description = "iOS_Shortcut")
@JsonPropertyOrder({
  IOsShortcut.JSON_PROPERTY_VERSION,
  IOsShortcut.JSON_PROPERTY_UPDATE,
  IOsShortcut.JSON_PROPERTY_LINK,
  IOsShortcut.JSON_PROPERTY_LINK_EN,
  IOsShortcut.JSON_PROPERTY_NOTE,
  IOsShortcut.JSON_PROPERTY_NOTE_EN
})

public class IOsShortcut implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_UPDATE = "update";
  private String update;

  public static final String JSON_PROPERTY_LINK = "link";
  private String link;

  public static final String JSON_PROPERTY_LINK_EN = "link_en";
  private String linkEn;

  public static final String JSON_PROPERTY_NOTE = "note";
  private String note;

  public static final String JSON_PROPERTY_NOTE_EN = "note_en";
  private String noteEn;


  public IOsShortcut version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Version
   * @return version
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Version")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public IOsShortcut update(String update) {
    
    this.update = update;
    return this;
  }

   /**
   * Update
   * @return update
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Update")
  @JsonProperty(JSON_PROPERTY_UPDATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdate() {
    return update;
  }


  public void setUpdate(String update) {
    this.update = update;
  }


  public IOsShortcut link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Link
   * @return link
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Link")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public IOsShortcut linkEn(String linkEn) {
    
    this.linkEn = linkEn;
    return this;
  }

   /**
   * Link En
   * @return linkEn
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Link En")
  @JsonProperty(JSON_PROPERTY_LINK_EN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLinkEn() {
    return linkEn;
  }


  public void setLinkEn(String linkEn) {
    this.linkEn = linkEn;
  }


  public IOsShortcut note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * Note
   * @return note
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Note")
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public IOsShortcut noteEn(String noteEn) {
    
    this.noteEn = noteEn;
    return this;
  }

   /**
   * Note En
   * @return noteEn
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Note En")
  @JsonProperty(JSON_PROPERTY_NOTE_EN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNoteEn() {
    return noteEn;
  }


  public void setNoteEn(String noteEn) {
    this.noteEn = noteEn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IOsShortcut iosShortcut = (IOsShortcut) o;
    return Objects.equals(this.version, iosShortcut.version) &&
        Objects.equals(this.update, iosShortcut.update) &&
        Objects.equals(this.link, iosShortcut.link) &&
        Objects.equals(this.linkEn, iosShortcut.linkEn) &&
        Objects.equals(this.note, iosShortcut.note) &&
        Objects.equals(this.noteEn, iosShortcut.noteEn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, update, link, linkEn, note, noteEn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IOsShortcut {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    linkEn: ").append(toIndentedString(linkEn)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    noteEn: ").append(toIndentedString(noteEn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

