/*
 * Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.AnyOfstringnull;

/**
 * ResponseModel
 */
@ApiModel(description = "ResponseModel")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-19T06:19:02.654880600-07:00[America/Los_Angeles]")
public class ResponseModel {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private Integer code = 200;

  public static final String SERIALIZED_NAME_ROUTER = "router";
  @SerializedName(SERIALIZED_NAME_ROUTER)
  private String router = "";

  public static final String SERIALIZED_NAME_PARAMS = "params";
  @SerializedName(SERIALIZED_NAME_PARAMS)
  private String params;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private AnyOfstringnull data = null;


  public ResponseModel code(Integer code) {
    
    this.code = code;
    return this;
  }

   /**
   * Code，HTTP status code | HTTP状态码
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code，HTTP status code | HTTP状态码")

  public Integer getCode() {
    return code;
  }


  public void setCode(Integer code) {
    this.code = code;
  }


  public ResponseModel router(String router) {
    
    this.router = router;
    return this;
  }

   /**
   * Router，The endpoint that generated this response | 生成此响应的端点
   * @return router
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Router，The endpoint that generated this response | 生成此响应的端点")

  public String getRouter() {
    return router;
  }


  public void setRouter(String router) {
    this.router = router;
  }


  public ResponseModel params(String params) {
    
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParams() {
    return params;
  }


  public void setParams(String params) {
    this.params = params;
  }


  public ResponseModel data(AnyOfstringnull data) {
    
    this.data = data;
    return this;
  }

   /**
   * Data，The response data | 响应数据
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Data，The response data | 响应数据")

  public AnyOfstringnull getData() {
    return data;
  }


  public void setData(AnyOfstringnull data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseModel responseModel = (ResponseModel) o;
    return Objects.equals(this.code, responseModel.code) &&
        Objects.equals(this.router, responseModel.router) &&
        Objects.equals(this.params, responseModel.params) &&
        Objects.equals(this.data, responseModel.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, router, params, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseModel {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    router: ").append(toIndentedString(router)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

