/*
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TikTok_APP_V3_Home_Feed
 */
@ApiModel(description = "TikTok_APP_V3_Home_Feed")
@JsonPropertyOrder({
  TikTokAppV3HomeFeed.JSON_PROPERTY_COOKIE
})

public class TikTokAppV3HomeFeed implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_COOKIE = "cookie";
  private String cookie = "";


  public TikTokAppV3HomeFeed cookie(String cookie) {
    
    this.cookie = cookie;
    return this;
  }

   /**
   * Cookie，用户自己的cookie，可选参数，用于接口返回数据的个性化推荐。/ User&#39;s own cookie, optional parameter, used for personalized recommendations of interface return data.
   * @return cookie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cookie，用户自己的cookie，可选参数，用于接口返回数据的个性化推荐。/ User's own cookie, optional parameter, used for personalized recommendations of interface return data.")
  @JsonProperty(JSON_PROPERTY_COOKIE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCookie() {
    return cookie;
  }


  public void setCookie(String cookie) {
    this.cookie = cookie;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TikTokAppV3HomeFeed tikTokAppV3HomeFeed = (TikTokAppV3HomeFeed) o;
    return Objects.equals(this.cookie, tikTokAppV3HomeFeed.cookie);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cookie);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TikTokAppV3HomeFeed {\n");
    sb.append("    cookie: ").append(toIndentedString(cookie)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

