/*
 * Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.HttpValidationError;
import org.openapitools.client.model.ResponseModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DouyinAppV3ApiApi
 */
@Ignore
public class DouyinAppV3ApiApiTest {

    private final DouyinAppV3ApiApi api = new DouyinAppV3ApiApi();

    
    /**
     * 获取指定关键词的综合搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_general_search_result）/Get comprehensive search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_general_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的综合搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 - sort_type: 0:综合排序 1:最多点赞 2:最新发布 - publish_time: 0:不限 1:最近一天 7:最近一周 180:最近半年 - filter_duration: 0:不限 0-1:1分钟以内 1-5:1-5分钟 5-10000:5分钟以上 - content_type: 0:不限 1:视频 2:图片 3:文章 ### 返回: - 综合搜索结果  # [English] ### Purpose: - Get comprehensive search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. - sort_type: 0: Comprehensive sorting 1: Most likes 2: Latest release - publish_time: 0: Unlimited 1: Last day 7: Last week 180: Last half year - filter_duration: 0: Unlimited 0-1: Within 1 minute 1-5: 1-5 minutes 5-10000: More than 5 minutes - content_type: 0: Unlimited 1: Video 2: Picture 3: Article ### Return: - Comprehensive search results  # [示例/Example] keyword &#x3D; \&quot;中华娘\&quot; offset &#x3D; 0 count &#x3D; 20 sort_type &#x3D; \&quot;0\&quot; publish_time &#x3D; \&quot;0\&quot; filter_duration &#x3D; \&quot;0\&quot; content_type &#x3D; \&quot;0\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchGeneralSearchResultApiV1DouyinAppV3FetchGeneralSearchResultGetTest() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        String sortType = null;
        String publishTime = null;
        String filterDuration = null;
        String contentType = null;
        ResponseModel response = api.fetchGeneralSearchResultApiV1DouyinAppV3FetchGeneralSearchResultGet(keyword, offset, count, sortType, publishTime, filterDuration, contentType);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的综合搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_general_search_result）/Get comprehensive search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_general_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的综合搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 - sort_type: 0:综合排序 1:最多点赞 2:最新发布 - publish_time: 0:不限 1:最近一天 7:最近一周 180:最近半年 - filter_duration: 0:不限 0-1:1分钟以内 1-5:1-5分钟 5-10000:5分钟以上 - content_type: 0:不限 1:视频 2:图片 3:文章 ### 返回: - 综合搜索结果  # [English] ### Purpose: - Get comprehensive search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. - sort_type: 0: Comprehensive sorting 1: Most likes 2: Latest release - publish_time: 0: Unlimited 1: Last day 7: Last week 180: Last half year - filter_duration: 0: Unlimited 0-1: Within 1 minute 1-5: 1-5 minutes 5-10000: More than 5 minutes - content_type: 0: Unlimited 1: Video 2: Picture 3: Article ### Return: - Comprehensive search results  # [示例/Example] keyword &#x3D; \&quot;中华娘\&quot; offset &#x3D; 0 count &#x3D; 20 sort_type &#x3D; \&quot;0\&quot; publish_time &#x3D; \&quot;0\&quot; filter_duration &#x3D; \&quot;0\&quot; content_type &#x3D; \&quot;0\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchGeneralSearchResultApiV1DouyinAppV3FetchGeneralSearchResultGet_0Test() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        String sortType = null;
        String publishTime = null;
        String filterDuration = null;
        String contentType = null;
        ResponseModel response = api.fetchGeneralSearchResultApiV1DouyinAppV3FetchGeneralSearchResultGet_0(keyword, offset, count, sortType, publishTime, filterDuration, contentType);

        // TODO: test validations
    }
    
    /**
     * 获取指定话题的详情数据/Get details of specified hashtag
     *
     * # [中文] ### 用途: - 获取指定话题的详情数据 ### 参数: - ch_id: 话题id ### 返回: - 话题详情数据  # [English] ### Purpose: - Get details of specified hashtag ### Parameters: - ch_id: Hashtag id ### Return: - Hashtag details data  # [示例/Example] ch_id &#x3D; 1575791821492238
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHashtagDetailApiV1DouyinAppV3FetchHashtagDetailGetTest() throws ApiException {
        Integer chId = null;
        ResponseModel response = api.fetchHashtagDetailApiV1DouyinAppV3FetchHashtagDetailGet(chId);

        // TODO: test validations
    }
    
    /**
     * 获取指定话题的详情数据/Get details of specified hashtag
     *
     * # [中文] ### 用途: - 获取指定话题的详情数据 ### 参数: - ch_id: 话题id ### 返回: - 话题详情数据  # [English] ### Purpose: - Get details of specified hashtag ### Parameters: - ch_id: Hashtag id ### Return: - Hashtag details data  # [示例/Example] ch_id &#x3D; 1575791821492238
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHashtagDetailApiV1DouyinAppV3FetchHashtagDetailGet_0Test() throws ApiException {
        Integer chId = null;
        ResponseModel response = api.fetchHashtagDetailApiV1DouyinAppV3FetchHashtagDetailGet_0(chId);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的话题搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_hashtag_search_result）/Get hashtag search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_hashtag_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的话题搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 话题搜索结果  # [English] ### Purpose: - Get hashtag search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Hashtag search results  # [示例/Example] keyword &#x3D; \&quot;中华娘\&quot; offset &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHashtagSearchResultApiV1DouyinAppV3FetchHashtagSearchResultGetTest() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        ResponseModel response = api.fetchHashtagSearchResultApiV1DouyinAppV3FetchHashtagSearchResultGet(keyword, offset, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的话题搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_hashtag_search_result）/Get hashtag search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_hashtag_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的话题搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 话题搜索结果  # [English] ### Purpose: - Get hashtag search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Hashtag search results  # [示例/Example] keyword &#x3D; \&quot;中华娘\&quot; offset &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHashtagSearchResultApiV1DouyinAppV3FetchHashtagSearchResultGet_0Test() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        ResponseModel response = api.fetchHashtagSearchResultApiV1DouyinAppV3FetchHashtagSearchResultGet_0(keyword, offset, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定话题的作品数据/Get video list of specified hashtag
     *
     * # [中文] ### 用途: - 获取指定话题的作品数据 ### 参数: - ch_id: 话题id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - sort_type: 0:综合排序 1:最多点赞 2:最新发布 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 话题作品数据  # [English] ### Purpose: - Get video list of specified hashtag ### Parameters: - ch_id: Hashtag id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - sort_type: 0: Comprehensive sorting 1: Most likes 2: Latest release - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Hashtag video list data  # [示例/Example] ch_id &#x3D; 1575791821492238 cursor &#x3D; 0 sort_type &#x3D; 0 count &#x3D; 10
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHashtagVideoListApiV1DouyinAppV3FetchHashtagVideoListGetTest() throws ApiException {
        String chId = null;
        Integer cursor = null;
        Integer sortType = null;
        Integer count = null;
        ResponseModel response = api.fetchHashtagVideoListApiV1DouyinAppV3FetchHashtagVideoListGet(chId, cursor, sortType, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定话题的作品数据/Get video list of specified hashtag
     *
     * # [中文] ### 用途: - 获取指定话题的作品数据 ### 参数: - ch_id: 话题id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - sort_type: 0:综合排序 1:最多点赞 2:最新发布 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 话题作品数据  # [English] ### Purpose: - Get video list of specified hashtag ### Parameters: - ch_id: Hashtag id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - sort_type: 0: Comprehensive sorting 1: Most likes 2: Latest release - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Hashtag video list data  # [示例/Example] ch_id &#x3D; 1575791821492238 cursor &#x3D; 0 sort_type &#x3D; 0 count &#x3D; 10
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHashtagVideoListApiV1DouyinAppV3FetchHashtagVideoListGet_0Test() throws ApiException {
        String chId = null;
        Integer cursor = null;
        Integer sortType = null;
        Integer count = null;
        ResponseModel response = api.fetchHashtagVideoListApiV1DouyinAppV3FetchHashtagVideoListGet_0(chId, cursor, sortType, count);

        // TODO: test validations
    }
    
    /**
     * 获取抖音品牌热榜具体分类数据/Get Douyin brand hot search list detail data
     *
     * # [中文] ### 用途: - 获取抖音品牌热榜具体分类数据 ### 参数: - category_id: 分类id ### 返回: - 品牌热搜榜具体分类数据  # [English] ### Purpose: - Get Douyin brand hot search list detail data ### Parameters: - category_id: Category id ### Return: - Hot brand search list detail data  # [示例/Example] category_id &#x3D; 10
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHotBrandSearchApiV1DouyinAppV3FetchBrandHotSearchListDetailGetTest() throws ApiException {
        Integer categoryId = null;
        ResponseModel response = api.fetchHotBrandSearchApiV1DouyinAppV3FetchBrandHotSearchListDetailGet(categoryId);

        // TODO: test validations
    }
    
    /**
     * 获取抖音品牌热榜具体分类数据/Get Douyin brand hot search list detail data
     *
     * # [中文] ### 用途: - 获取抖音品牌热榜具体分类数据 ### 参数: - category_id: 分类id ### 返回: - 品牌热搜榜具体分类数据  # [English] ### Purpose: - Get Douyin brand hot search list detail data ### Parameters: - category_id: Category id ### Return: - Hot brand search list detail data  # [示例/Example] category_id &#x3D; 10
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHotBrandSearchApiV1DouyinAppV3FetchBrandHotSearchListDetailGet_0Test() throws ApiException {
        Integer categoryId = null;
        ResponseModel response = api.fetchHotBrandSearchApiV1DouyinAppV3FetchBrandHotSearchListDetailGet_0(categoryId);

        // TODO: test validations
    }
    
    /**
     * 获取抖音品牌热榜分类数据/Get Douyin brand hot search list data
     *
     * # [中文] ### 用途: - 获取抖音品牌热榜分类数据 ### 返回: - 品牌热搜榜分类数据  # [English] ### Purpose: - Get Douyin brand hot search category data ### Return: - Hot brand search category data  # [示例/Example] pass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHotBrandSearchCategoryApiV1DouyinAppV3FetchBrandHotSearchListGetTest() throws ApiException {
        ResponseModel response = api.fetchHotBrandSearchCategoryApiV1DouyinAppV3FetchBrandHotSearchListGet();

        // TODO: test validations
    }
    
    /**
     * 获取抖音品牌热榜分类数据/Get Douyin brand hot search list data
     *
     * # [中文] ### 用途: - 获取抖音品牌热榜分类数据 ### 返回: - 品牌热搜榜分类数据  # [English] ### Purpose: - Get Douyin brand hot search category data ### Return: - Hot brand search category data  # [示例/Example] pass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHotBrandSearchCategoryApiV1DouyinAppV3FetchBrandHotSearchListGet_0Test() throws ApiException {
        ResponseModel response = api.fetchHotBrandSearchCategoryApiV1DouyinAppV3FetchBrandHotSearchListGet_0();

        // TODO: test validations
    }
    
    /**
     * 获取抖音热搜榜数据/Get Douyin hot search list data
     *
     * # [中文] ### 用途: - 获取抖音热搜榜数据 ### 返回: - 热搜榜数据  # [English] ### Purpose: - Get Douyin hot search list data ### Return: - Hot search list data  # [示例/Example] pass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHotSearchListApiV1DouyinAppV3FetchHotSearchListGetTest() throws ApiException {
        ResponseModel response = api.fetchHotSearchListApiV1DouyinAppV3FetchHotSearchListGet();

        // TODO: test validations
    }
    
    /**
     * 获取抖音热搜榜数据/Get Douyin hot search list data
     *
     * # [中文] ### 用途: - 获取抖音热搜榜数据 ### 返回: - 热搜榜数据  # [English] ### Purpose: - Get Douyin hot search list data ### Return: - Hot search list data  # [示例/Example] pass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchHotSearchListApiV1DouyinAppV3FetchHotSearchListGet_0Test() throws ApiException {
        ResponseModel response = api.fetchHotSearchListApiV1DouyinAppV3FetchHotSearchListGet_0();

        // TODO: test validations
    }
    
    /**
     * 获取抖音直播热搜榜数据/Get Douyin live hot search list data
     *
     * # [中文] ### 用途: - 获取抖音直播热搜榜数据 ### 返回: - 直播热搜榜数据  # [English] ### Purpose: - Get Douyin live hot search list data ### Return: - Live hot search list data  # [示例/Example] pass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchLiveHotSearchListApiV1DouyinAppV3FetchLiveHotSearchListGetTest() throws ApiException {
        ResponseModel response = api.fetchLiveHotSearchListApiV1DouyinAppV3FetchLiveHotSearchListGet();

        // TODO: test validations
    }
    
    /**
     * 获取抖音直播热搜榜数据/Get Douyin live hot search list data
     *
     * # [中文] ### 用途: - 获取抖音直播热搜榜数据 ### 返回: - 直播热搜榜数据  # [English] ### Purpose: - Get Douyin live hot search list data ### Return: - Live hot search list data  # [示例/Example] pass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchLiveHotSearchListApiV1DouyinAppV3FetchLiveHotSearchListGet_0Test() throws ApiException {
        ResponseModel response = api.fetchLiveHotSearchListApiV1DouyinAppV3FetchLiveHotSearchListGet_0();

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的直播搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_live_search_result）/Get live search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_live_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的直播搜索结果 ### 参数: - keyword: 关键词 - cursor: 偏移量，从0开始，每次请求从上次请求返回响应中的cursor中获取。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 直播搜索结果  # [English] ### Purpose: - Get live search results of specified keywords ### Parameters: - keyword: Keyword - cursor: Offset, starting from 0, each request gets from the cursor in the response returned by the last request. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Live search results  # [示例/Example] keyword &#x3D; \&quot;小米商城\&quot; cursor &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchLiveSearchResultApiV1DouyinAppV3FetchLiveSearchResultGetTest() throws ApiException {
        String keyword = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchLiveSearchResultApiV1DouyinAppV3FetchLiveSearchResultGet(keyword, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的直播搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_live_search_result）/Get live search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_live_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的直播搜索结果 ### 参数: - keyword: 关键词 - cursor: 偏移量，从0开始，每次请求从上次请求返回响应中的cursor中获取。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 直播搜索结果  # [English] ### Purpose: - Get live search results of specified keywords ### Parameters: - keyword: Keyword - cursor: Offset, starting from 0, each request gets from the cursor in the response returned by the last request. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Live search results  # [示例/Example] keyword &#x3D; \&quot;小米商城\&quot; cursor &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchLiveSearchResultApiV1DouyinAppV3FetchLiveSearchResultGet_0Test() throws ApiException {
        String keyword = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchLiveSearchResultApiV1DouyinAppV3FetchLiveSearchResultGet_0(keyword, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 批量获取视频信息/Batch Get Video Information
     *
     * # [中文] ### 用途: - 批量获取视频信息，支持图文、视频等，一次性最多支持10个视频，此接口收费固定价格为0.001$ * 10 &#x3D; 0.01$一次。 ### 参数: - aweme_ids: 作品id列表，最多支持10个作品id。 ### 返回: - 作品数据  # [English] ### Purpose: - Batch Get Video Information, support photo, video, etc., up to 10 videos at a time, this interface charges a fixed price of 0.001$ * 10 &#x3D; 0.01$ each time. ### Parameters: - aweme_ids: List of video ids, up to 10 video ids are supported. ### Return: - Video data  # [示例/Example] aweme_ids &#x3D; [\&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;, \&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;, \&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;, \&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;, \&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;]
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMultiVideoApiV1DouyinAppV3FetchMultiVideoPostTest() throws ApiException {
        List<String> requestBody = null;
        ResponseModel response = api.fetchMultiVideoApiV1DouyinAppV3FetchMultiVideoPost(requestBody);

        // TODO: test validations
    }
    
    /**
     * 批量获取视频信息/Batch Get Video Information
     *
     * # [中文] ### 用途: - 批量获取视频信息，支持图文、视频等，一次性最多支持10个视频，此接口收费固定价格为0.001$ * 10 &#x3D; 0.01$一次。 ### 参数: - aweme_ids: 作品id列表，最多支持10个作品id。 ### 返回: - 作品数据  # [English] ### Purpose: - Batch Get Video Information, support photo, video, etc., up to 10 videos at a time, this interface charges a fixed price of 0.001$ * 10 &#x3D; 0.01$ each time. ### Parameters: - aweme_ids: List of video ids, up to 10 video ids are supported. ### Return: - Video data  # [示例/Example] aweme_ids &#x3D; [\&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;, \&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;, \&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;, \&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;, \&quot;7372484719365098803\&quot;, \&quot;7126745726494821640\&quot;]
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMultiVideoApiV1DouyinAppV3FetchMultiVideoPost_0Test() throws ApiException {
        List<String> requestBody = null;
        ResponseModel response = api.fetchMultiVideoApiV1DouyinAppV3FetchMultiVideoPost_0(requestBody);

        // TODO: test validations
    }
    
    /**
     * 获取指定音乐的详情数据/Get details of specified music
     *
     * # [中文] ### 用途: - 获取指定音乐的详情数据 ### 参数: - music_id: 音乐id ### 返回: - 音乐详情数据  # [English] ### Purpose: - Get details of specified music ### Parameters: - music_id: Music id ### Return: - Music details data  # [示例/Example] music_id &#x3D; \&quot;7136850194742315016\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMusicDetailApiV1DouyinAppV3FetchMusicDetailGetTest() throws ApiException {
        String musicId = null;
        ResponseModel response = api.fetchMusicDetailApiV1DouyinAppV3FetchMusicDetailGet(musicId);

        // TODO: test validations
    }
    
    /**
     * 获取指定音乐的详情数据/Get details of specified music
     *
     * # [中文] ### 用途: - 获取指定音乐的详情数据 ### 参数: - music_id: 音乐id ### 返回: - 音乐详情数据  # [English] ### Purpose: - Get details of specified music ### Parameters: - music_id: Music id ### Return: - Music details data  # [示例/Example] music_id &#x3D; \&quot;7136850194742315016\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMusicDetailApiV1DouyinAppV3FetchMusicDetailGet_0Test() throws ApiException {
        String musicId = null;
        ResponseModel response = api.fetchMusicDetailApiV1DouyinAppV3FetchMusicDetailGet_0(musicId);

        // TODO: test validations
    }
    
    /**
     * 获取抖音音乐热榜数据/Get Douyin music hot search list data
     *
     * # [中文] ### 用途: - 获取抖音音乐热榜数据 ### 返回: - 音乐热搜榜数据  # [English] ### Purpose: - Get Douyin music hot search list data ### Return: - Music hot search list data  # [示例/Example] pass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMusicHotSearchListApiV1DouyinAppV3FetchMusicHotSearchListGetTest() throws ApiException {
        ResponseModel response = api.fetchMusicHotSearchListApiV1DouyinAppV3FetchMusicHotSearchListGet();

        // TODO: test validations
    }
    
    /**
     * 获取抖音音乐热榜数据/Get Douyin music hot search list data
     *
     * # [中文] ### 用途: - 获取抖音音乐热榜数据 ### 返回: - 音乐热搜榜数据  # [English] ### Purpose: - Get Douyin music hot search list data ### Return: - Music hot search list data  # [示例/Example] pass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMusicHotSearchListApiV1DouyinAppV3FetchMusicHotSearchListGet_0Test() throws ApiException {
        ResponseModel response = api.fetchMusicHotSearchListApiV1DouyinAppV3FetchMusicHotSearchListGet_0();

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的音乐搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_music_search_result）/Get music search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_music_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的音乐搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 音乐搜索结果  # [English] ### Purpose: - Get music search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Music search results  # [示例/Example] keyword &#x3D; \&quot;中华娘\&quot; offset &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMusicSearchResultApiV1DouyinAppV3FetchMusicSearchResultGetTest() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        ResponseModel response = api.fetchMusicSearchResultApiV1DouyinAppV3FetchMusicSearchResultGet(keyword, offset, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的音乐搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_music_search_result）/Get music search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_music_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的音乐搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 音乐搜索结果  # [English] ### Purpose: - Get music search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Music search results  # [示例/Example] keyword &#x3D; \&quot;中华娘\&quot; offset &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMusicSearchResultApiV1DouyinAppV3FetchMusicSearchResultGet_0Test() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        ResponseModel response = api.fetchMusicSearchResultApiV1DouyinAppV3FetchMusicSearchResultGet_0(keyword, offset, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定音乐的视频列表数据/Get video list of specified music
     *
     * # [中文] ### 用途: - 获取指定音乐的视频列表数据 ### 参数: - music_id: 音乐id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 音乐视频列表数据  # [English] ### Purpose: - Get video list of specified music ### Parameters: - music_id: Music id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Music video list data  # [示例/Example] music_id &#x3D; \&quot;7136850194742315016\&quot; cursor &#x3D; 0 count &#x3D; 10
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMusicVideoListApiV1DouyinAppV3FetchMusicVideoListGetTest() throws ApiException {
        String musicId = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchMusicVideoListApiV1DouyinAppV3FetchMusicVideoListGet(musicId, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定音乐的视频列表数据/Get video list of specified music
     *
     * # [中文] ### 用途: - 获取指定音乐的视频列表数据 ### 参数: - music_id: 音乐id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 音乐视频列表数据  # [English] ### Purpose: - Get video list of specified music ### Parameters: - music_id: Music id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Music video list data  # [示例/Example] music_id &#x3D; \&quot;7136850194742315016\&quot; cursor &#x3D; 0 count &#x3D; 10
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMusicVideoListApiV1DouyinAppV3FetchMusicVideoListGet_0Test() throws ApiException {
        String musicId = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchMusicVideoListApiV1DouyinAppV3FetchMusicVideoListGet_0(musicId, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取单个作品数据/Get single video data
     *
     * # [中文] ### 用途: - 获取单个作品数据，支持图文、视频等。 ### 参数: - aweme_id: 作品id ### 返回: - 作品数据  # [English] ### Purpose: - Get single video data, support photo, video, etc. ### Parameters: - aweme_id: Video id ### Return: - Video data  # [示例/Example] aweme_id &#x3D; \&quot;7372484719365098803\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchOneVideoApiV1DouyinAppV3FetchOneVideoGetTest() throws ApiException {
        String awemeId = null;
        ResponseModel response = api.fetchOneVideoApiV1DouyinAppV3FetchOneVideoGet(awemeId);

        // TODO: test validations
    }
    
    /**
     * 获取单个作品数据/Get single video data
     *
     * # [中文] ### 用途: - 获取单个作品数据，支持图文、视频等。 ### 参数: - aweme_id: 作品id ### 返回: - 作品数据  # [English] ### Purpose: - Get single video data, support photo, video, etc. ### Parameters: - aweme_id: Video id ### Return: - Video data  # [示例/Example] aweme_id &#x3D; \&quot;7372484719365098803\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchOneVideoApiV1DouyinAppV3FetchOneVideoGet_0Test() throws ApiException {
        String awemeId = null;
        ResponseModel response = api.fetchOneVideoApiV1DouyinAppV3FetchOneVideoGet_0(awemeId);

        // TODO: test validations
    }
    
    /**
     * 根据分享链接获取单个作品数据/Get single video data by sharing link
     *
     * # [中文] ### 用途: - 根据分享链接获取单个作品数据 ### 参数: - share_url: 分享链接 ### 返回: - 作品数据  # [English] ### Purpose: - Get single video data by sharing link ### Parameters: - share_url: Share link ### Return: - Video data  # [示例/Example] share_url &#x3D; \&quot;https://v.douyin.com/e3x2fjE/\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchOneVideoByShareUrlApiV1DouyinAppV3FetchOneVideoByShareUrlGetTest() throws ApiException {
        String shareUrl = null;
        ResponseModel response = api.fetchOneVideoByShareUrlApiV1DouyinAppV3FetchOneVideoByShareUrlGet(shareUrl);

        // TODO: test validations
    }
    
    /**
     * 根据分享链接获取单个作品数据/Get single video data by sharing link
     *
     * # [中文] ### 用途: - 根据分享链接获取单个作品数据 ### 参数: - share_url: 分享链接 ### 返回: - 作品数据  # [English] ### Purpose: - Get single video data by sharing link ### Parameters: - share_url: Share link ### Return: - Video data  # [示例/Example] share_url &#x3D; \&quot;https://v.douyin.com/e3x2fjE/\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchOneVideoByShareUrlApiV1DouyinAppV3FetchOneVideoByShareUrlGet_0Test() throws ApiException {
        String shareUrl = null;
        ResponseModel response = api.fetchOneVideoByShareUrlApiV1DouyinAppV3FetchOneVideoByShareUrlGet_0(shareUrl);

        // TODO: test validations
    }
    
    /**
     * 获取用户粉丝列表/Get user fans list
     *
     * # [中文] ### 用途: - 获取用户粉丝列表 ### 参数: - sec_user_id: 用户sec_user_id - max_time: 最大时间戳，默认为0，后续从返回数据中获取，用于翻页。 - count: 数量，默认为20，建议保持不变。 ### 返回: - 粉丝列表  # [English] ### Purpose: - Get user fans list ### Parameters: - sec_user_id: User sec_user_id - max_time: Maximum timestamp, default is 0, get from the returned data later, used for paging. - count: Number, default is 20, it is recommended to keep it unchanged. ### Return: - Fans list  # [示例/Example] sec_user &#x3D; \&quot;MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70\&quot; max_time &#x3D; \&quot;0\&quot; count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserFansListApiV1DouyinAppV3FetchUserFansListGetTest() throws ApiException {
        String secUserId = null;
        String maxTime = null;
        Integer count = null;
        ResponseModel response = api.fetchUserFansListApiV1DouyinAppV3FetchUserFansListGet(secUserId, maxTime, count);

        // TODO: test validations
    }
    
    /**
     * 获取用户粉丝列表/Get user fans list
     *
     * # [中文] ### 用途: - 获取用户粉丝列表 ### 参数: - sec_user_id: 用户sec_user_id - max_time: 最大时间戳，默认为0，后续从返回数据中获取，用于翻页。 - count: 数量，默认为20，建议保持不变。 ### 返回: - 粉丝列表  # [English] ### Purpose: - Get user fans list ### Parameters: - sec_user_id: User sec_user_id - max_time: Maximum timestamp, default is 0, get from the returned data later, used for paging. - count: Number, default is 20, it is recommended to keep it unchanged. ### Return: - Fans list  # [示例/Example] sec_user &#x3D; \&quot;MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70\&quot; max_time &#x3D; \&quot;0\&quot; count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserFansListApiV1DouyinAppV3FetchUserFansListGet_0Test() throws ApiException {
        String secUserId = null;
        String maxTime = null;
        Integer count = null;
        ResponseModel response = api.fetchUserFansListApiV1DouyinAppV3FetchUserFansListGet_0(secUserId, maxTime, count);

        // TODO: test validations
    }
    
    /**
     * 获取用户关注列表/Get user following list
     *
     * # [中文] ### 用途: - 获取用户关注列表 ### 参数: - sec_user_id: 用户sec_user_id - max_time: 最大时间戳，默认为0，后续从返回数据中获取，用于翻页。 - count: 数量，默认为20，建议保持不变。 ### 返回: - 关注列表  # [English] ### Purpose: - Get user following list ### Parameters: - sec_user_id: User sec_user_id - max_time: Maximum timestamp, default is 0, get from the returned data later, used for paging. - count: Number, default is 20, it is recommended to keep it unchanged. ### Return: - Following list  # [示例/Example] sec_user &#x3D; \&quot;MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70\&quot; max_time &#x3D; \&quot;0\&quot; count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserFollowingListApiV1DouyinAppV3FetchUserFollowingListGetTest() throws ApiException {
        String secUserId = null;
        String maxTime = null;
        Integer count = null;
        ResponseModel response = api.fetchUserFollowingListApiV1DouyinAppV3FetchUserFollowingListGet(secUserId, maxTime, count);

        // TODO: test validations
    }
    
    /**
     * 获取用户关注列表/Get user following list
     *
     * # [中文] ### 用途: - 获取用户关注列表 ### 参数: - sec_user_id: 用户sec_user_id - max_time: 最大时间戳，默认为0，后续从返回数据中获取，用于翻页。 - count: 数量，默认为20，建议保持不变。 ### 返回: - 关注列表  # [English] ### Purpose: - Get user following list ### Parameters: - sec_user_id: User sec_user_id - max_time: Maximum timestamp, default is 0, get from the returned data later, used for paging. - count: Number, default is 20, it is recommended to keep it unchanged. ### Return: - Following list  # [示例/Example] sec_user &#x3D; \&quot;MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70\&quot; max_time &#x3D; \&quot;0\&quot; count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserFollowingListApiV1DouyinAppV3FetchUserFollowingListGet_0Test() throws ApiException {
        String secUserId = null;
        String maxTime = null;
        Integer count = null;
        ResponseModel response = api.fetchUserFollowingListApiV1DouyinAppV3FetchUserFollowingListGet_0(secUserId, maxTime, count);

        // TODO: test validations
    }
    
    /**
     * 获取用户喜欢作品数据/Get user like video data
     *
     * # [中文] ### 用途: - 获取用户喜欢作品数据 ### 参数: - sec_user_id: 用户sec_user_id - max_cursor: 最大游标，用于翻页，第一页为0，第二页为第一次响应中的max_cursor值。 - count: 最大数量 ### 返回: - 用户作品数据  # [English] ### Purpose: - Get user like video data ### Parameters: - sec_user_id: User sec_user_id - max_cursor: Maximum cursor, used for paging, the first page is 0, the second page is the max_cursor value in the first response. - count: Maximum count number ### Return: - User video data  # [示例/Example] sec_user_id &#x3D; \&quot;MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y\&quot; max_cursor &#x3D; 0 counts &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserLikeVideosApiV1DouyinAppV3FetchUserLikeVideosGetTest() throws ApiException {
        String secUserId = null;
        Integer maxCursor = null;
        Integer counts = null;
        ResponseModel response = api.fetchUserLikeVideosApiV1DouyinAppV3FetchUserLikeVideosGet(secUserId, maxCursor, counts);

        // TODO: test validations
    }
    
    /**
     * 获取用户喜欢作品数据/Get user like video data
     *
     * # [中文] ### 用途: - 获取用户喜欢作品数据 ### 参数: - sec_user_id: 用户sec_user_id - max_cursor: 最大游标，用于翻页，第一页为0，第二页为第一次响应中的max_cursor值。 - count: 最大数量 ### 返回: - 用户作品数据  # [English] ### Purpose: - Get user like video data ### Parameters: - sec_user_id: User sec_user_id - max_cursor: Maximum cursor, used for paging, the first page is 0, the second page is the max_cursor value in the first response. - count: Maximum count number ### Return: - User video data  # [示例/Example] sec_user_id &#x3D; \&quot;MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y\&quot; max_cursor &#x3D; 0 counts &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserLikeVideosApiV1DouyinAppV3FetchUserLikeVideosGet_0Test() throws ApiException {
        String secUserId = null;
        Integer maxCursor = null;
        Integer counts = null;
        ResponseModel response = api.fetchUserLikeVideosApiV1DouyinAppV3FetchUserLikeVideosGet_0(secUserId, maxCursor, counts);

        // TODO: test validations
    }
    
    /**
     * 获取用户主页作品数据/Get user homepage video data
     *
     * # [中文] ### 用途: - 获取用户主页作品数据 ### 参数: - sec_user_id: 用户sec_user_id - max_cursor: 最大游标，用于翻页，第一页为0，第二页为第一次响应中的max_cursor值。 - count: 最大数量 ### 返回: - 用户作品数据  # [English] ### Purpose: - Get user homepage video data ### Parameters: - sec_user_id: User sec_user_id - max_cursor: Maximum cursor, used for paging, the first page is 0, the second page is the max_cursor value in the first response. - count: Maximum count number ### Return: - User video data  # [示例/Example] sec_user_id &#x3D; \&quot;MS4wLjABAAAANXSltcLCzDGmdNFI2Q_QixVTr67NiYzjKOIP5s03CAE\&quot; max_cursor &#x3D; 0 counts &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserPostVideosApiV1DouyinAppV3FetchUserPostVideosGetTest() throws ApiException {
        String secUserId = null;
        Integer maxCursor = null;
        Integer count = null;
        ResponseModel response = api.fetchUserPostVideosApiV1DouyinAppV3FetchUserPostVideosGet(secUserId, maxCursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取用户主页作品数据/Get user homepage video data
     *
     * # [中文] ### 用途: - 获取用户主页作品数据 ### 参数: - sec_user_id: 用户sec_user_id - max_cursor: 最大游标，用于翻页，第一页为0，第二页为第一次响应中的max_cursor值。 - count: 最大数量 ### 返回: - 用户作品数据  # [English] ### Purpose: - Get user homepage video data ### Parameters: - sec_user_id: User sec_user_id - max_cursor: Maximum cursor, used for paging, the first page is 0, the second page is the max_cursor value in the first response. - count: Maximum count number ### Return: - User video data  # [示例/Example] sec_user_id &#x3D; \&quot;MS4wLjABAAAANXSltcLCzDGmdNFI2Q_QixVTr67NiYzjKOIP5s03CAE\&quot; max_cursor &#x3D; 0 counts &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserPostVideosApiV1DouyinAppV3FetchUserPostVideosGet_0Test() throws ApiException {
        String secUserId = null;
        Integer maxCursor = null;
        Integer count = null;
        ResponseModel response = api.fetchUserPostVideosApiV1DouyinAppV3FetchUserPostVideosGet_0(secUserId, maxCursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的用户搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_user_search_result_v2）/Get user search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_user_search_result_v2)
     *
     * # [中文] ### 用途: - 获取指定关键词的用户搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 - douyin_user_fans(粉丝数量):     - \&quot;\&quot;: 不限     - \&quot;0_1k\&quot;: 1000以下     - \&quot;1k_1w\&quot;: 1000-1万     - \&quot;1w_10w\&quot;: 1w-10w     - \&quot;10w_100w\&quot;: 10w-100w     - \&quot;100w_\&quot;: 100w以上 - douyin_user_type(用户类型，请使用英文而不是中文):     - \&quot;\&quot;: 不限     - \&quot;common_user\&quot;: 普通用户     - \&quot;enterprise_user\&quot;: 企业认证     - \&quot;personal_user\&quot;: 个人认证 ### 返回: - 用户搜索结果  # [English] ### Purpose: - Get user search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. - douyin_user_fans(Fans):     - \&quot;\&quot;: Unlimited     - \&quot;0_1k\&quot;: Less than 1000     - \&quot;1k_1w\&quot;: 1000-10,000     - \&quot;1w_10w\&quot;: 10,000-100,000     - \&quot;10w_100w\&quot;: 100,000-1,000,000     - \&quot;100w_\&quot;: More than 1,000,000 - douyin_user_type(User type, please use English instead of Chinese):     - \&quot;\&quot;: Unlimited     - \&quot;common_user\&quot;: Common user     - \&quot;enterprise_user\&quot;: Enterprise certification     - \&quot;personal_user\&quot;: Personal certification ### Return: - User search results  # [示例/Example] keyword &#x3D; \&quot;动漫\&quot; offset &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserSearchResultApiV1DouyinAppV3FetchUserSearchResultGetTest() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        String douyinUserFans = null;
        String douyinUserType = null;
        ResponseModel response = api.fetchUserSearchResultApiV1DouyinAppV3FetchUserSearchResultGet(keyword, offset, count, douyinUserFans, douyinUserType);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的用户搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_user_search_result_v2）/Get user search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_user_search_result_v2)
     *
     * # [中文] ### 用途: - 获取指定关键词的用户搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 - douyin_user_fans(粉丝数量):     - \&quot;\&quot;: 不限     - \&quot;0_1k\&quot;: 1000以下     - \&quot;1k_1w\&quot;: 1000-1万     - \&quot;1w_10w\&quot;: 1w-10w     - \&quot;10w_100w\&quot;: 10w-100w     - \&quot;100w_\&quot;: 100w以上 - douyin_user_type(用户类型，请使用英文而不是中文):     - \&quot;\&quot;: 不限     - \&quot;common_user\&quot;: 普通用户     - \&quot;enterprise_user\&quot;: 企业认证     - \&quot;personal_user\&quot;: 个人认证 ### 返回: - 用户搜索结果  # [English] ### Purpose: - Get user search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. - douyin_user_fans(Fans):     - \&quot;\&quot;: Unlimited     - \&quot;0_1k\&quot;: Less than 1000     - \&quot;1k_1w\&quot;: 1000-10,000     - \&quot;1w_10w\&quot;: 10,000-100,000     - \&quot;10w_100w\&quot;: 100,000-1,000,000     - \&quot;100w_\&quot;: More than 1,000,000 - douyin_user_type(User type, please use English instead of Chinese):     - \&quot;\&quot;: Unlimited     - \&quot;common_user\&quot;: Common user     - \&quot;enterprise_user\&quot;: Enterprise certification     - \&quot;personal_user\&quot;: Personal certification ### Return: - User search results  # [示例/Example] keyword &#x3D; \&quot;动漫\&quot; offset &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserSearchResultApiV1DouyinAppV3FetchUserSearchResultGet_0Test() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        String douyinUserFans = null;
        String douyinUserType = null;
        ResponseModel response = api.fetchUserSearchResultApiV1DouyinAppV3FetchUserSearchResultGet_0(keyword, offset, count, douyinUserFans, douyinUserType);

        // TODO: test validations
    }
    
    /**
     * 获取单个视频评论数据/Get single video comments data
     *
     * # [中文] ### 用途: - 获取单个视频评论数据 ### 参数: - aweme_id: 作品id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 评论数据  # [English] ### Purpose: - Get single video comments data ### Parameters: - aweme_id: Video id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Comments data  # [示例/Example] aweme_id &#x3D; \&quot;7372484719365098803\&quot; cursor &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoCommentsApiV1DouyinAppV3FetchVideoCommentsGetTest() throws ApiException {
        String awemeId = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchVideoCommentsApiV1DouyinAppV3FetchVideoCommentsGet(awemeId, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取单个视频评论数据/Get single video comments data
     *
     * # [中文] ### 用途: - 获取单个视频评论数据 ### 参数: - aweme_id: 作品id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 评论数据  # [English] ### Purpose: - Get single video comments data ### Parameters: - aweme_id: Video id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Comments data  # [示例/Example] aweme_id &#x3D; \&quot;7372484719365098803\&quot; cursor &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoCommentsApiV1DouyinAppV3FetchVideoCommentsGet_0Test() throws ApiException {
        String awemeId = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchVideoCommentsApiV1DouyinAppV3FetchVideoCommentsGet_0(awemeId, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定视频的评论回复数据/Get comment replies data of specified video
     *
     * # [中文] ### 用途: - 获取指定视频的评论回复数据 ### 参数: - item_id: 作品id - comment_id: 评论id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 评论回复数据  # [English] ### Purpose: - Get comment replies data of specified video ### Parameters: - item_id: Video id - comment_id: Comment id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Comment replies data  # [示例/Example] aweme_id &#x3D; \&quot;7354666303006723354\&quot; comment_id &#x3D; \&quot;7354669356632638218\&quot; cursor &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoCommentsReplyApiV1DouyinAppV3FetchVideoCommentRepliesGetTest() throws ApiException {
        String itemId = null;
        String commentId = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchVideoCommentsReplyApiV1DouyinAppV3FetchVideoCommentRepliesGet(itemId, commentId, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定视频的评论回复数据/Get comment replies data of specified video
     *
     * # [中文] ### 用途: - 获取指定视频的评论回复数据 ### 参数: - item_id: 作品id - comment_id: 评论id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 评论回复数据  # [English] ### Purpose: - Get comment replies data of specified video ### Parameters: - item_id: Video id - comment_id: Comment id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Comment replies data  # [示例/Example] aweme_id &#x3D; \&quot;7354666303006723354\&quot; comment_id &#x3D; \&quot;7354669356632638218\&quot; cursor &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoCommentsReplyApiV1DouyinAppV3FetchVideoCommentRepliesGet_0Test() throws ApiException {
        String itemId = null;
        String commentId = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchVideoCommentsReplyApiV1DouyinAppV3FetchVideoCommentRepliesGet_0(itemId, commentId, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取抖音视频合集详情数据/Get Douyin video mix detail data
     *
     * # [中文] ### 用途: - 获取抖音视频合集详情数据 ### 参数: - mix_id: 合集id ### 返回: - 视频合集详情数据  # [English] ### Purpose: - Get Douyin video mix detail data ### Parameters: - mix_id: Mix id ### Return: - Video mix detail data  # [示例/Example] mix_id &#x3D; \&quot;7302011174286002217\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoMixDetailApiV1DouyinAppV3FetchVideoMixDetailGetTest() throws ApiException {
        String mixId = null;
        ResponseModel response = api.fetchVideoMixDetailApiV1DouyinAppV3FetchVideoMixDetailGet(mixId);

        // TODO: test validations
    }
    
    /**
     * 获取抖音视频合集详情数据/Get Douyin video mix detail data
     *
     * # [中文] ### 用途: - 获取抖音视频合集详情数据 ### 参数: - mix_id: 合集id ### 返回: - 视频合集详情数据  # [English] ### Purpose: - Get Douyin video mix detail data ### Parameters: - mix_id: Mix id ### Return: - Video mix detail data  # [示例/Example] mix_id &#x3D; \&quot;7302011174286002217\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoMixDetailApiV1DouyinAppV3FetchVideoMixDetailGet_0Test() throws ApiException {
        String mixId = null;
        ResponseModel response = api.fetchVideoMixDetailApiV1DouyinAppV3FetchVideoMixDetailGet_0(mixId);

        // TODO: test validations
    }
    
    /**
     * 获取抖音视频合集作品列表数据/Get Douyin video mix post list data
     *
     * # [中文] ### 用途: - 获取抖音视频合集作品列表数据 ### 参数: - mix_id: 合集id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 视频合集作品列表数据  # [English] ### Purpose: - Get Douyin video mix post list data ### Parameters: - mix_id: Mix id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Video mix post list data  # [示例/Example] mix_id &#x3D; \&quot;7302011174286002217\&quot; cursor &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoMixPostListApiV1DouyinAppV3FetchVideoMixPostListGetTest() throws ApiException {
        String mixId = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchVideoMixPostListApiV1DouyinAppV3FetchVideoMixPostListGet(mixId, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取抖音视频合集作品列表数据/Get Douyin video mix post list data
     *
     * # [中文] ### 用途: - 获取抖音视频合集作品列表数据 ### 参数: - mix_id: 合集id - cursor: 游标，用于翻页，第一页为0，第二页为第一次响应中的cursor值。 - count: 数量，请保持默认，否则会出现BUG。 ### 返回: - 视频合集作品列表数据  # [English] ### Purpose: - Get Douyin video mix post list data ### Parameters: - mix_id: Mix id - cursor: Cursor, used for paging, the first page is 0, the second page is the cursor value in the first response. - count: Number Please keep the default, otherwise there will be BUG. ### Return: - Video mix post list data  # [示例/Example] mix_id &#x3D; \&quot;7302011174286002217\&quot; cursor &#x3D; 0 count &#x3D; 20
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoMixPostListApiV1DouyinAppV3FetchVideoMixPostListGet_0Test() throws ApiException {
        String mixId = null;
        Integer cursor = null;
        Integer count = null;
        ResponseModel response = api.fetchVideoMixPostListApiV1DouyinAppV3FetchVideoMixPostListGet_0(mixId, cursor, count);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的视频搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_video_search_result）/Get video search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_video_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的视频搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 - sort_type: 0:综合排序 1:最多点赞 2:最新发布 - publish_time: 0:不限 1:最近一天 7:最近一周 180:最近半年 - filter_duration: 0:不限 0-1:1分钟以内 1-5:1-5分钟 5-10000:5分钟以上 ### 返回: - 视频搜索结果  # [English] ### Purpose: - Get video search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. - sort_type: 0: Comprehensive sorting 1: Most likes 2: Latest release - publish_time: 0: Unlimited 1: Last day 7: Last week 180: Last half year - filter_duration: 0: Unlimited 0-1: Within 1 minute 1-5: 1-5 minutes 5-10000: More than 5 minutes ### Return: - Video search results  # [示例/Example] keyword &#x3D; \&quot;中华娘\&quot; offset &#x3D; 0 count &#x3D; 20 sort_type &#x3D; \&quot;0\&quot; publish_time &#x3D; \&quot;0\&quot; filter_duration &#x3D; \&quot;0\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoSearchResultApiV1DouyinAppV3FetchVideoSearchResultGetTest() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        String sortType = null;
        String publishTime = null;
        String filterDuration = null;
        ResponseModel response = api.fetchVideoSearchResultApiV1DouyinAppV3FetchVideoSearchResultGet(keyword, offset, count, sortType, publishTime, filterDuration);

        // TODO: test validations
    }
    
    /**
     * 获取指定关键词的视频搜索结果（弃用，替代接口：/api/v1/douyin/web/fetch_video_search_result）/Get video search results of specified keywords (deprecated, alternative interface: /api/v1/douyin/web/fetch_video_search_result)
     *
     * # [中文] ### 用途: - 获取指定关键词的视频搜索结果 ### 参数: - keyword: 关键词 - offset: 偏移量 - count: 数量，请保持默认，否则会出现BUG。 - sort_type: 0:综合排序 1:最多点赞 2:最新发布 - publish_time: 0:不限 1:最近一天 7:最近一周 180:最近半年 - filter_duration: 0:不限 0-1:1分钟以内 1-5:1-5分钟 5-10000:5分钟以上 ### 返回: - 视频搜索结果  # [English] ### Purpose: - Get video search results of specified keywords ### Parameters: - keyword: Keyword - offset: Offset - count: Number Please keep the default, otherwise there will be BUG. - sort_type: 0: Comprehensive sorting 1: Most likes 2: Latest release - publish_time: 0: Unlimited 1: Last day 7: Last week 180: Last half year - filter_duration: 0: Unlimited 0-1: Within 1 minute 1-5: 1-5 minutes 5-10000: More than 5 minutes ### Return: - Video search results  # [示例/Example] keyword &#x3D; \&quot;中华娘\&quot; offset &#x3D; 0 count &#x3D; 20 sort_type &#x3D; \&quot;0\&quot; publish_time &#x3D; \&quot;0\&quot; filter_duration &#x3D; \&quot;0\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoSearchResultApiV1DouyinAppV3FetchVideoSearchResultGet_0Test() throws ApiException {
        String keyword = null;
        Integer offset = null;
        Integer count = null;
        String sortType = null;
        String publishTime = null;
        String filterDuration = null;
        ResponseModel response = api.fetchVideoSearchResultApiV1DouyinAppV3FetchVideoSearchResultGet_0(keyword, offset, count, sortType, publishTime, filterDuration);

        // TODO: test validations
    }
    
    /**
     * 根据视频ID获取作品的统计数据/Get the statistical data of the work according to the video ID
     *
     * # [中文] ### 用途: - 根据视频ID获取作品的统计数据 - 抖音大多数接口已经不再返回作品的播放数，只能通过此接口获取。 - 可以获取到的统计有：     - 点赞数（digg_count）     - 下载数（download_count）     - 播放数（play_count）     - 分享数（share_count） ### 参数: - aweme_ids: 作品id，支持多个视频id，用逗号隔开即可，不能超过2个，单个也可以，则无需逗号。 ### 返回: - 作品统计数据  # [English] ### Purpose: - Get the statistical data of the Post according to the video ID - Most of the Douyin interfaces no longer return the number of plays of the Post, and can only be obtained through this interface. - List of statistics that can be obtained:     - Like count (digg_count)     - Download count (download_count)     - Play count (play_count)     - Share count (share_count) ### Parameters: - aweme_ids: Video id, supports multiple video ids, separated by commas, no more than 2, single is also possible, no need for commas. ### Return: - Post statistics data  # [示例/Example] aweme_ids &#x3D; \&quot;7372484719365098803,7126745726494821640\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoStatisticsApiV1DouyinAppV3FetchVideoStatisticsGetTest() throws ApiException {
        String awemeIds = null;
        ResponseModel response = api.fetchVideoStatisticsApiV1DouyinAppV3FetchVideoStatisticsGet(awemeIds);

        // TODO: test validations
    }
    
    /**
     * 根据视频ID获取作品的统计数据/Get the statistical data of the work according to the video ID
     *
     * # [中文] ### 用途: - 根据视频ID获取作品的统计数据 - 抖音大多数接口已经不再返回作品的播放数，只能通过此接口获取。 - 可以获取到的统计有：     - 点赞数（digg_count）     - 下载数（download_count）     - 播放数（play_count）     - 分享数（share_count） ### 参数: - aweme_ids: 作品id，支持多个视频id，用逗号隔开即可，不能超过2个，单个也可以，则无需逗号。 ### 返回: - 作品统计数据  # [English] ### Purpose: - Get the statistical data of the Post according to the video ID - Most of the Douyin interfaces no longer return the number of plays of the Post, and can only be obtained through this interface. - List of statistics that can be obtained:     - Like count (digg_count)     - Download count (download_count)     - Play count (play_count)     - Share count (share_count) ### Parameters: - aweme_ids: Video id, supports multiple video ids, separated by commas, no more than 2, single is also possible, no need for commas. ### Return: - Post statistics data  # [示例/Example] aweme_ids &#x3D; \&quot;7372484719365098803,7126745726494821640\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVideoStatisticsApiV1DouyinAppV3FetchVideoStatisticsGet_0Test() throws ApiException {
        String awemeIds = null;
        ResponseModel response = api.fetchVideoStatisticsApiV1DouyinAppV3FetchVideoStatisticsGet_0(awemeIds);

        // TODO: test validations
    }
    
    /**
     * 生成抖音短链接/Generate Douyin short link
     *
     * # [中文] ### 用途: - 生成抖音短链接 ### 参数: - url: 抖音链接 ### 返回: - 短链接数据  # [English] ### Purpose: - Generate Douyin short link ### Parameters: - url: Douyin link ### Return: - Short link data  # [示例/Example] url &#x3D; \&quot;https://www.douyin.com/passport/web/logout/\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void generateDouyinShortUrlApiV1DouyinAppV3GenerateDouyinShortUrlGetTest() throws ApiException {
        String url = null;
        ResponseModel response = api.generateDouyinShortUrlApiV1DouyinAppV3GenerateDouyinShortUrlGet(url);

        // TODO: test validations
    }
    
    /**
     * 生成抖音短链接/Generate Douyin short link
     *
     * # [中文] ### 用途: - 生成抖音短链接 ### 参数: - url: 抖音链接 ### 返回: - 短链接数据  # [English] ### Purpose: - Generate Douyin short link ### Parameters: - url: Douyin link ### Return: - Short link data  # [示例/Example] url &#x3D; \&quot;https://www.douyin.com/passport/web/logout/\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void generateDouyinShortUrlApiV1DouyinAppV3GenerateDouyinShortUrlGet_0Test() throws ApiException {
        String url = null;
        ResponseModel response = api.generateDouyinShortUrlApiV1DouyinAppV3GenerateDouyinShortUrlGet_0(url);

        // TODO: test validations
    }
    
    /**
     * 生成抖音视频分享二维码/Generate Douyin video share QR code
     *
     * # [中文] ### 用途: - 生成抖音视频分享二维码 ### 参数: - object_id: 作品id或作者uid ### 返回: - 二维码数据  # [English] ### Purpose: - Generate Douyin video share QR code ### Parameters: - object_id: Video id or author uid ### Return: - QR code data  # [示例/Example] object_id &#x3D; \&quot;7348044435755846962\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void generateDouyinVideoShareQrcodeApiV1DouyinAppV3GenerateDouyinVideoShareQrcodeGetTest() throws ApiException {
        String objectId = null;
        ResponseModel response = api.generateDouyinVideoShareQrcodeApiV1DouyinAppV3GenerateDouyinVideoShareQrcodeGet(objectId);

        // TODO: test validations
    }
    
    /**
     * 生成抖音视频分享二维码/Generate Douyin video share QR code
     *
     * # [中文] ### 用途: - 生成抖音视频分享二维码 ### 参数: - object_id: 作品id或作者uid ### 返回: - 二维码数据  # [English] ### Purpose: - Generate Douyin video share QR code ### Parameters: - object_id: Video id or author uid ### Return: - QR code data  # [示例/Example] object_id &#x3D; \&quot;7348044435755846962\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void generateDouyinVideoShareQrcodeApiV1DouyinAppV3GenerateDouyinVideoShareQrcodeGet_0Test() throws ApiException {
        String objectId = null;
        ResponseModel response = api.generateDouyinVideoShareQrcodeApiV1DouyinAppV3GenerateDouyinVideoShareQrcodeGet_0(objectId);

        // TODO: test validations
    }
    
    /**
     * 获取指定用户的信息/Get information of specified user
     *
     * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - sec_user_id: 用户sec_user_id ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - sec_user_id: User sec_user_id ### Return: - User information  # [示例/Example] sec_user_id &#x3D; \&quot;MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handlerUserProfileApiV1DouyinAppV3HandlerUserProfileGetTest() throws ApiException {
        String secUserId = null;
        ResponseModel response = api.handlerUserProfileApiV1DouyinAppV3HandlerUserProfileGet(secUserId);

        // TODO: test validations
    }
    
    /**
     * 获取指定用户的信息/Get information of specified user
     *
     * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - sec_user_id: 用户sec_user_id ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - sec_user_id: User sec_user_id ### Return: - User information  # [示例/Example] sec_user_id &#x3D; \&quot;MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handlerUserProfileApiV1DouyinAppV3HandlerUserProfileGet_0Test() throws ApiException {
        String secUserId = null;
        ResponseModel response = api.handlerUserProfileApiV1DouyinAppV3HandlerUserProfileGet_0(secUserId);

        // TODO: test validations
    }
    
}
