/*
 * Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.IOsShortcut;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IOsShortcutApi
 */
@Ignore
public class IOsShortcutApiTest {

    private final IOsShortcutApi api = new IOsShortcutApi();

    
    /**
     * 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getShortcutApiV1IosShortcutShortcutGetTest() throws ApiException {
        IOsShortcut response = api.getShortcutApiV1IosShortcutShortcutGet();

        // TODO: test validations
    }
    
    /**
     * 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getShortcutApiV1IosShortcutShortcutGet_0Test() throws ApiException {
        IOsShortcut response = api.getShortcutApiV1IosShortcutShortcutGet_0();

        // TODO: test validations
    }
    
}
