/*
 * Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.HttpValidationError;
import org.openapitools.client.model.ResponseModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WeiboWebApiApi
 */
@Ignore
public class WeiboWebApiApiTest {

    private final WeiboWebApiApi api = new WeiboWebApiApi();

    
    /**
     * 获取单个作品数据/Get single video data
     *
     * # [中文] ### 用途: - 获取单个作品数据 ### 参数: - id: 作品id ### 返回: - 作品数据  # [English] ### Purpose: - Get single video data ### Parameters: - id: Post id ### Return: - Post data  # [示例/Example] itemId &#x3D; \&quot;5008127060086127\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchPostDetailApiV1WeiboWebFetchPostDetailGetTest() throws ApiException {
        String id = null;
        ResponseModel response = api.fetchPostDetailApiV1WeiboWebFetchPostDetailGet(id);

        // TODO: test validations
    }
    
    /**
     * 获取单个作品数据/Get single video data
     *
     * # [中文] ### 用途: - 获取单个作品数据 ### 参数: - id: 作品id ### 返回: - 作品数据  # [English] ### Purpose: - Get single video data ### Parameters: - id: Post id ### Return: - Post data  # [示例/Example] itemId &#x3D; \&quot;5008127060086127\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchPostDetailApiV1WeiboWebFetchPostDetailGet_0Test() throws ApiException {
        String id = null;
        ResponseModel response = api.fetchPostDetailApiV1WeiboWebFetchPostDetailGet_0(id);

        // TODO: test validations
    }
    
    /**
     * 获取用户信息/Get user information
     *
     * # [中文] ### 用途: - 获取用户信息 ### 参数: - uid: 用户id ### 返回: - 用户信息  # [English] ### Purpose: - Get user information ### Parameters: - uid: User id ### Return: - User information  # [示例/Example] uid &#x3D; \&quot;7277477906\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserInfoApiV1WeiboWebFetchUserInfoGetTest() throws ApiException {
        String uid = null;
        ResponseModel response = api.fetchUserInfoApiV1WeiboWebFetchUserInfoGet(uid);

        // TODO: test validations
    }
    
    /**
     * 获取用户信息/Get user information
     *
     * # [中文] ### 用途: - 获取用户信息 ### 参数: - uid: 用户id ### 返回: - 用户信息  # [English] ### Purpose: - Get user information ### Parameters: - uid: User id ### Return: - User information  # [示例/Example] uid &#x3D; \&quot;7277477906\&quot;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserInfoApiV1WeiboWebFetchUserInfoGet_0Test() throws ApiException {
        String uid = null;
        ResponseModel response = api.fetchUserInfoApiV1WeiboWebFetchUserInfoGet_0(uid);

        // TODO: test validations
    }
    
    /**
     * 获取微博用户文章数据/Get Weibo user article data
     *
     * # [中文] ### 用途: - 获取微博用户文章数据 ### 参数: - uid: 用户id - page: 页数 - feature: 特征 ### 返回: - 用户文章数据  # [English] ### Purpose: - Get Weibo user article data ### Parameters: - uid: User id - page: Page number - feature: Feature ### Return: - User article data  # [示例/Example] uid &#x3D; \&quot;7277477906\&quot; page &#x3D; 1 feature &#x3D; 0
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserPostsApiV1WeiboWebFetchUserPostsGetTest() throws ApiException {
        String uid = null;
        Integer page = null;
        Integer feature = null;
        ResponseModel response = api.fetchUserPostsApiV1WeiboWebFetchUserPostsGet(uid, page, feature);

        // TODO: test validations
    }
    
    /**
     * 获取微博用户文章数据/Get Weibo user article data
     *
     * # [中文] ### 用途: - 获取微博用户文章数据 ### 参数: - uid: 用户id - page: 页数 - feature: 特征 ### 返回: - 用户文章数据  # [English] ### Purpose: - Get Weibo user article data ### Parameters: - uid: User id - page: Page number - feature: Feature ### Return: - User article data  # [示例/Example] uid &#x3D; \&quot;7277477906\&quot; page &#x3D; 1 feature &#x3D; 0
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchUserPostsApiV1WeiboWebFetchUserPostsGet_0Test() throws ApiException {
        String uid = null;
        Integer page = null;
        Integer feature = null;
        ResponseModel response = api.fetchUserPostsApiV1WeiboWebFetchUserPostsGet_0(uid, page, feature);

        // TODO: test validations
    }
    
}
